### ISSUE TITLE
Swift 2.0 Issues Not working at all.

### ISSUE THREAD

**Issue by thedangler** [vikmeup/SCLAlertView-Swift#100]
Easy to use?
installed via cocoapods
I can't get it to work, can't import SCAlertView
Can't just call it like you are in your examples

**Comment by y25zhao** [comment]
Same here. Please fix it. Appreciate that.

**Comment by y25zhao** [comment]
Please update the pod spec so that the new version gets published for supporting swift 2.0. thank you very much

**Comment by ewan34500** [comment]
In your pod , write this : 
pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git'

**Comment by dancingbush** [comment]
Changes in swift 2 weren't that many, I have made and got project running, not sure how to upload changes though as haven't use GIT much

**Comment by vikmeup** [comment]
- September 23rd, 10:48: Push for `SCLAlertView 0.4.2' initiated.
- September 23rd, 10:48: Push for `SCLAlertView 0.4.2' has been pushed (2.812916978 s).

**Comment by y25zhao** [comment]
Thanks @vikmeup You rock!
