### ISSUE TITLE
AlertView does not release from memory

### ISSUE THREAD

**Issue by nbwar** [vikmeup/SCLAlertView-Swift#105]
After opening an alert view it is retained in memory and not deinitialized. A simple test is to put a `print` statement inside of  `deinit` in `SCLAertView` and it never gets called. This leads to multiple zombie instances of alertview objects floating around. Most noticeable when interacting with NSNotificationCenter for Keyboard events. Instances start to build up.

**Comment by orangecoding** [comment]
Nice catch. Why not fixing this by yourself?

**Comment by vikmeup** [comment]
@nbwar feel free to submit pull request. Thanks

**Comment by Spilly** [comment]
I am seeing this issue as well. I don't see any circular references that jump out at me, but will take a further look in a bit.

**Comment by Asinox** [comment]
Any updates about this ?

**Comment by ridvank** [comment]
Is there any update yet?

**Comment by guidove** [comment]
Any update on this? This is really a tricky issue. In my case (i guess for everyone), because the alertView is not deinitialized also the ViewController showing the alert  is not reinitialised from memory, which could cause huge memory leaks in Apps. 

Tried to find the cause, but no luck. Even tried setting the alertView to nil on viewWillDisappear of the calling VC, but that didn't do it either.

**Comment by guidove** [comment]
Did a bit more digging after I commented and FOUND IT! 
It's the actions / target,selectors of the buttons. 
Add below code to the completion block of the hideView - AnimateWithDuration function:

for button in self.buttons {
    button.action = nil
    button.target = nil
    button.selector = nil
}

**Comment by pragmaticpat** [comment]
@guidove - show some open-source love and submit a pull req if you have it fixed.

**Comment by guidove** [comment]
Just submitted. It's my first pull request on github so hope I did it correct.

**Comment by vikmeup** [comment]
#125

**Comment by pragmaticpat** [comment]
BOOM! Nice work @guidove - thanks for the quick re: @vikmeup

**Comment by Asinox** [comment]
Nice!, update the Pod please

**Comment by polis80cy** [comment]
I think this fix is to blame for issue #130.

**Comment by iTSangar** [comment]
error still going on 
Xcode 7.2.1 
Occurred:  clicking the button more than once
