### ISSUE TITLE
hideView() called twice in func buttonTapped(btn:SCLButton)

### ISSUE THREAD

**Issue by damonYuan** [vikmeup/SCLAlertView-Swift#111]
there is a possibility that the btn.selector.description == "hideView", which make hideView() called twice, and if dismiss block added, will also be called twice.

**Comment by pragmaticpat** [comment]
i'm seeing this behavior as well @damonYuan

**Comment by pragmaticpat** [comment]
Submitted #119 to address this. @damonYuan feel free to test with my fork.

**Comment by vikmeup** [comment]
@pragmaticpat merged. Thanks
