### ISSUE TITLE
change kTextFieldHeight value not work

### ISSUE THREAD

**Issue by malkabani** [vikmeup/SCLAlertView-Swift#116]
hi
i need to change textfield height so i change value of kTextFieldHeight to be 100 but nothing change
and if you put any value no change appear

but you can change background color of textfield

is there any related code or issue that prevent textfield to change it's size????
thank you.

**Comment by matheusleite** [comment]
let textField : UITextField = alert.addTextField("Comente...")
        var frameRect = textField.frame
        frameRect.size.height = 70
        textField.frame = frameRect

this work for me
