### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ravigill** [vikmeup/SCLAlertView-Swift#117]
It would be great if the following feature could be added. I have created a extension to achieve this.

<b>prepare the alert without showing it right-away and only show it by explicitly calling show() somewhere else</b>.

Usecase scenario 1
  1. Users sees a screen with table
  2. User clicks on a table cell & <b>the Alert is prepared</b>
  3. User is taken to a new screen (another View controller)
  4. Users goes back to the original screen with table
  5. User is presented with the <b>previously prepared Alert</b>

Mock example
```swift
class MyViewController: UIViewController {
    private var alertViewResponder: SCLAlertViewResponder?
    ...
    func userClickedSomewhere(){
          ...
          self.alertViewResponder = SCLAlertView().prepareTitle(
                "Congratulations", // Title of view
                subTitle: "Operation successfully completed.", // String of view
                duration: 2.0, // Duration to show before closing automatically, default: 0.0
                completeText: "Done", // Optional button value, default: ""
                style: .Success, // Styles - see below.
                colorStyle: 0xA429FF,
                colorTextButton: 0xFFFFFF
            )
    }
    ...
    func showAlert(){
        self.alertViewResponder!.show()
    }
}
```

**Comment by vikmeup** [comment]
I don't see a need for it. you can just SCLAlertView(). and then set values before calling `showInfo` function. 

But, feel free to send PR. I'm closing this issue for now

**Comment by ravigill** [comment]
The need is debatable. But this is not important for us at the moment, so i'm fine with the close.
