### ISSUE TITLE
Using Selector("buttonTapped") dismisses alertview

### ISSUE THREAD

**Issue by Jackson0111** [vikmeup/SCLAlertView-Swift#118]
In the example project, in the showSuccess function when you tap the first button, it doesn't dismiss the alertview. I'm also using alertview.addButton with Selector("buttonTapped") but it dismisses the alertview. I literally just copy paste the same code in the example project and it doesn't dismiss the view! I've been trying to figure this out for hours... Here is my code, please take a look: 

    let alert = SCLAlertView()
    var email = UITextField()
    var password = UITextField()

    func showAlertView() {
        
        email = alert.addTextField("Email")
        
        password = alert.addTextField("Password")
        
        alert.addButton("Log In", target: self, selector: Selector("loginButtonTapped"))
        
        alert.addButton("Sign Up", target: self, selector: Selector("signupButtonTapped"))
        
        alert.addButton("maybe later") {
            
            self.alert.dismissViewControllerAnimated(true, completion: nil)
                        
        }
        
        alert.showCloseButton = false
        
        alert.showTitle("Log In", subTitle: "log in", style: .Notice, colorStyle: 0x3c78d8)
    }

showAlerView() is called in viewDidLoad(), and the viewcontroller is not the  initial viewcontroller, that's the only difference between my code and the example project. Also in my loginButtonTapped() function, I only have a print( "button tapped" ) function.

**Comment by vikmeup** [comment]
Please try update sample project. This problem should be fixed now.
