### ISSUE TITLE
SCLAlertView move up/down of screen while tapping on UITextField

### ISSUE THREAD

**Issue by ipaddr** [vikmeup/SCLAlertView-Swift#124]
If we add more then one textfield to SCLAlertView, let say two textfield. if we tapping on the first textfield, and then tapping on the second textfield, and then back again tapping on the first textfield, the SCLAlertView will moving down of the screen. 
If we tapping outside of SCLAlertView, then a keyboard will be hidden, and then if we repeat previous step, then now the SCLAlertView moving up of the screen.

**Comment by ipaddr** [comment]
<img width="319" alt="screen shot 2016-01-07 at 10 59 55 am" src="https://cloud.githubusercontent.com/assets/5902218/12162065/007c5106-b530-11e5-9a31-cd1d64f1b4fd.png">

**Comment by ipaddr** [comment]
<img width="321" alt="screen shot 2016-01-07 at 11 00 02 am" src="https://cloud.githubusercontent.com/assets/5902218/12162088/4cef94da-b530-11e5-9d9e-b359c53379de.png">

**Comment by ipaddr** [comment]
<img width="325" alt="screen shot 2016-01-07 at 11 19 35 am" src="https://cloud.githubusercontent.com/assets/5902218/12162114/95344eca-b530-11e5-88dc-627512bfc379.png">

**Comment by Hanggi** [comment]
I met this problem, to use my keyboard, the dialog will go down, and can't touch it.If I use system keyboard, it will be fine.

**Comment by polis80cy** [comment]
I have this too @ipaddr, with v0.5.

**Comment by Vesla** [comment]
I think it's due to the fact that it calls the fund keyboardWillShow, i will do a pull request today for this, the problem is solved for me on local

**Comment by jcarroll3** [comment]
Confirmed issue on 0.5.1

**Comment by RyanCodes** [comment]
@Vesla can you raise that Pull request?

**Comment by anzhehong** [comment]
@Vesla can you raise that Pull request?

**Comment by RyanCodes** [comment]
Temp fix go look at his branch and cherry pick the code into the local pod library. Remember it will reset when the library updates

**Comment by DanielChu** [comment]
Basic problem seems to be custom keyboards (Flesky etc.) does multiple calls to keyboardWillShow with very weird frame values. 

I've got a fix in my fork. Basically re-wrote it so now the alert box will only move if keyboard overlaps it and never moves so far up that the top of the content is out of the view.

Also just created a pull request for it.

**Comment by tharak** [comment]
happening with me too, if you change you keyboard to emojis it will go down at each tap if you are unlucky enough you app will be stuck and the user will have to close the app

**Comment by tenfu** [comment]
because two animate , before Vesla fixed, you can try
[textField performSelector:@selector(becomeFirstResponder) withObject:nil afterDelay:.4];

**Comment by Vesla** [comment]
Im back to an iOS project and I still need this, is the issue still present on last version? I will do a new pull request to satisfy the author.

**Comment by Vesla** [comment]
Is there anyone meeting this bug ? Can't replicate it
It looks like it's fixed
Maybe this should be closed unless someone still have it
