### ISSUE TITLE
Custom design

### ISSUE THREAD

**Issue by joshuawright11** [vikmeup/SCLAlertView-Swift#126]
Setting the background of the content view, the image, button fonts, etc

**Comment by devJoshLopez** [comment]
The only thing keeping me from using this awesome alertview is not being able to figure out how to change the image icon. If anyone knows how please let me know!

**Comment by vikmeup** [comment]
@devJoshLopez it supports image icon now, please update to latest version. Thanks

**Comment by vikmeup** [comment]
@joshuawright11 feel free to send pull request.

**Comment by devJoshLopez** [comment]
@vikmeup Hey Viktor, thank you for your response. I am new to swift, how would I go about changing the image icon in code? Thanks again. I really appreciate the work you are doing. Much love

**Comment by blazierkyle** [comment]
#171 Supports a custom subview, so you'd be able to supply a UIView that goes under the title and above the buttons to customize any way you'd like.

**Comment by vikmeup** [comment]
@blazierkyle Thanks for contributing.
