### ISSUE TITLE
func buttonTapped - unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by polis80cy** [vikmeup/SCLAlertView-Swift#130]
The following code crashes with a fatal error: unexpectedly found nil while unwrapping an Optional value.
```
func buttonTapped(btn:SCLButton) {
        if btn.actionType == SCLActionType.Closure {
            btn.action()
        } else if btn.actionType == SCLActionType.Selector {
            let ctrl = UIControl()
            ctrl.sendAction(btn.selector, to:btn.target, forEvent:nil)
        } else {
            print("Unknow action type for button")
        }
        
        if(self.view.alpha != 0.0){ hideView() }
    }
```
the line that fails is 
 `ctrl.sendAction(btn.selector, to:btn.target, forEvent:nil)`

When I debug, selector and target are nil.

My implementation:
`SCLAlertView().showError("Sign up", subTitle: message as! String, closeButtonTitle: "OK", colorStyle: 0x4a5f70)`

I've noticed I only get the error the 2nd time round.

this is on latest v0.5.

**Comment by polis80cy** [comment]
It works if I surround it in a nil checking statement:

```
            if btn.selector != nil && btn.target != nil {
                ctrl.sendAction(btn.selector, to:btn.target, forEvent:nil)
            }

```

**Comment by gfelot** [comment]
I had the same error. I solve it by declaring a `let myAlert = SCLAlertView()` inside my func' scope and assign it at the end to where I wanted.
