### ISSUE TITLE
showTitle crash IF colorStyle == nil

### ISSUE THREAD

**Issue by sabiland** [vikmeup/SCLAlertView-Swift#131]
alertView.showTitle(title, subTitle: message, style: alertType, colorStyle: nil)

This call crashes if colorStyle is sent as == nil.

FIX:

static func yesNoAlerterCorrectColorStyle(alertType:SCLAlertViewStyle) -> UInt
    {
        switch alertType
        {
        case .Success:
            
            return 0x22B573
            
        case .Error:
            
            return 0xC1272D
            
        case .Notice:
            
            return 0x727375
            
        case .Warning:
            
            return 0xFFD110
            
        case .Info:
            
            return 0x2866BF
            
        case .Wait:
            
            return 0xD62DA5
            
        case .Edit:
            
            return 0xA429FF
            
        }
    }

**Comment by CrystalVisions** [comment]
How about just setting the default values to black color and white buttons? 
Default values are set in the convenience methods such as showEdit, showInfo etc.
`colorStyle: UInt?=0x000000, colorTextButton: UInt?=0xFFFFFF`

**Comment by vikmeup** [comment]
Could you submit pull request with this fix? Thanks

**Comment by vikmeup** [comment]
I think it's fixed now. Let me know if you still having that problem
