### ISSUE TITLE
Change only background color of closebutton

### ISSUE THREAD

**Issue by ArturSkachkov** [vikmeup/SCLAlertView-Swift#133]
as it is possible to change only the background color of closebutton? Backgrowd color оf other buttons set to leave viewcolor

**Comment by vikmeup** [comment]
```
let alert = SCLAlertView()
let button = alert.addButton("First Button", target:self, selector:Selector("firstButton"))
button.backgroundColor = UIColor.RedColor()
```

Now you have access to button property.

**Comment by ArturSkachkov** [comment]
It,s not work

**Comment by vikmeup** [comment]
```
let alert = SCLAlertView()
let button = alert.addButton("First Button", target:self, selector:Selector("firstButton"))
alert.showSuccess(kSuccessTitle, subTitle: kSubtitle)
button.backgroundColor = UIColor.redColor()
```
This solution will work.

**Comment by ArturSkachkov** [comment]
Виктор, спасибо огромное!


>Среда, 10 февраля 2016, 4:37 -08:00 от Viktor Radchenko <notifications@github.com>:
>
>let alert = SCLAlertView()
let button = alert.addButton("First Button", target:self, selector:Selector("firstButton"))
alert.showSuccess(kSuccessTitle, subTitle: kSubtitle)
button.backgroundColor = UIColor.redColor()
>This solution will work.
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Артур Скачков
тел.: +79510000903
artursk-2004@mail.ru

**Comment by saravananNV** [comment]
@ArturSkachkov 

 I want to change the background color of all buttons in scalertview.how can i change it

thanks

**Comment by ArturSkachkov** [comment]
All the buttons are the same color
In SCLAlertView.swift : 
`    public func caseOne(title: String, subTitle: String, closeButtonTitle:String?=nil, duration:NSTimeInterval=0.0, colorStyle: UInt=0xYOUR COLOR, colorTextButton: UInt=0xFFFFFF, circleIconImage: UIImage? = nil) -> SCLAlertViewResponder {
        return showTitle(title, subTitle: subTitle, duration: duration, completeText:closeButtonTitle, style: .progress16off, colorStyle: colorStyle, colorTextButton: colorTextButton, circleIconImage: circleIconImage)`
All buttons in different colors
 In your controller:
`            let alert = SCLAlertView()
            
            let button = alert.addButton("Rate on iTunes") {
            // Your Code
            }
             let button2 = alert.addButton("Send Us Feedback") {
            // Your Code
            }
            let button3 = alert.addButton("Cancel") {
                print("Cancel tapped")
            }
            alert.showRateApp("Rate This App!", subTitle: "Are you enjoying our app? ...")
            button.backgroundColor = UIColor(red: 100/255, green: 100/255, blue: 100/255, alpha: 1.0)
            button2.backgroundColor = UIColor(red: 200/255, green: 200/255, blue: 200/255, alpha: 1.0)
            button3.backgroundColor = UIColor(red: 250/255, green: 250/255, blue: 250/255, alpha: 1.0)
        }
`
