### ISSUE TITLE
Dismiss Alert When Tapping The Background View

### ISSUE THREAD

**Issue by jaytrixz** [vikmeup/SCLAlertView-Swift#136]
Please add this feature. Thanks.

**Comment by fulldecent** [comment]
This is called `shouldDismissOnTapOutside` in the Objective-C version

**Comment by chancyWu** [comment]
@ytakzk add this feature already. but now it's only in the example project, not in the master repo. refer to this [commit]
(https://github.com/vikmeup/SCLAlertView-Swift/commit/59ab8e12e66108a7b428c44f724b80f01882505e)

**Comment by vikmeup** [comment]
@chancyWu would you able to make that change and send PR? 
I would be great to only have one SCLAlertView.swift file, per your request :+1:

**Comment by chancyWu** [comment]
@vikmeup sure, i'll check and send PR later.

**Comment by jaytrixz** [comment]
Waiting for this to get released...thanks guys!

**Comment by ytakzk** [comment]
@chancyWu @vikmeup @jaytrixz I added the code to the master repo too.
