### ISSUE TITLE
Can I use a TextView instead of a TextField

### ISSUE THREAD

**Issue by MichaelCosmo** [vikmeup/SCLAlertView-Swift#137]
I just want to know if it's simply possible to use a TextView into an alert. Thanks.

**Comment by jaceee** [comment]
Looks like a feature request.
+1 for this.

**Comment by matheusleite** [comment]
+ 1 for this

**Comment by MichaelCosmo** [comment]
Any news??

**Comment by MichaelCosmo** [comment]
I've made the feature ;)
#168
