### ISSUE TITLE
Text label is truncating text 

### ISSUE THREAD

**Issue by MaxKramer** [vikmeup/SCLAlertView-Swift#143]
Hi,

When I try and display a 'wait' alert with the text set to 'finding your nearest venues', the text is truncated: 
<img width="312" alt="screen shot 2016-03-19 at 23 07 05" src="https://cloud.githubusercontent.com/assets/542953/13901791/50d14ba4-ee27-11e5-9c7a-c92937f1e54e.png">

**Comment by MaxKramer** [comment]
```
class func rc_ShowWaitNoButton(title: String, subtitle: String) -> SCLAlertViewResponder {
        let alert = SCLAlertView()
        alert.showCloseButton = false
        let responder = alert.showTitle(
            title,
            subTitle: subtitle,
            duration: 0, // Duration to show before closing automatically, default: 0.0
            completeText: "", // Optional button value, default: ""
            style: .Wait, // Styles - see below.
            colorStyle: 0xa3a1a1,
            colorTextButton: 0xFFFFFF
        )
        return responder
    }
```

**Comment by gfelot** [comment]
In the source code (if I refere to github) line 173.
Try to `labelTitle.numberOfLines = 1` to `= 0`

**Comment by MaxKramer** [comment]
@gfelot Already tried, the text is still truncated.

**Comment by vikmeup** [comment]
It's fixed in latest commits.
