### ISSUE TITLE
about showinfo

### ISSUE THREAD

**Issue by dsxNiubility** [vikmeup/SCLAlertView-Swift#145]
AlertView of showinfo has only one textFiled, can you support a custom to add more.  we want to use two    textFiled to edit name and pwd...

**Comment by vikmeup** [comment]
```swift
let alert = SCLAlertView()
let textField = alert.addTextField(title:"Enter your name")
textField.secureTextEntry = true
```

you should be able to set any property to UITextField

**Comment by danielideriba** [comment]
For Swift 4 is:

 textField.isSecureTextEntry = true
