### ISSUE TITLE
SCLAlertView goes down the screen on edit

### ISSUE THREAD

**Issue by gfelot** [vikmeup/SCLAlertView-Swift#152]
I have a weird behaviour if I had and a textView to my alertView.
On tap on the textView, the view goes down and don't goes up after hitting return.

See here on call
![img_0502](https://cloud.githubusercontent.com/assets/7879555/14084149/b0ad3e36-f519-11e5-9859-35fbe99ec4ed.png)

On tap into the textField
![img_0503](https://cloud.githubusercontent.com/assets/7879555/14084173/c4102e70-f519-11e5-99ee-eee241047fc7.png)

On hitting return
![img_0504](https://cloud.githubusercontent.com/assets/7879555/14084178/cd192cb0-f519-11e5-90d1-c919214b89b3.png)

**Comment by Shanlon** [comment]
I am also having this issue.

**Comment by golfguru1** [comment]
+1 also having this issue

**Comment by Twelve57** [comment]
The only solution I came up with is to make some changes in the SCLAlertView.swift file.
To be clear, my application is used on iPad Pro with a Smart Keyboard.

So the solution is to change the viewDidAppear and the viewDidDisappear methods.
And just comment the two lines started by : 
> NSNotificationCenter.defaultCenter

In fact after removing the listener managing the keyboard, this bug will never appear again.
I've not tested the solution with other cases or other devices and WITHOUT the Smart Keyboard.

**Comment by golfguru1** [comment]
@Twelve57 just tried that on an iPhone 6 and it the problem is gone. Thanks!
