### ISSUE TITLE
About the icons...

### ISSUE THREAD

**Issue by iiMshl** [vikmeup/SCLAlertView-Swift#155]
Is there a way to choose custom icon?
or no icon at all?

**Comment by iiMshl** [comment]
nvm I figured it out!... but I think you need to mention it in the README

**Comment by sdbarron** [comment]
@iiMshl  Could you either give the answer you figure out here - or, better yet, update the README and make a Pull Request? That would help the next person with the same question.  Thanks!

**Comment by iiMshl** [comment]
Alright I updated it and made a pull request

**Comment by sdbarron** [comment]
Thanks!  I find that the originators of these things are often too close to know what-all needs to be included in ReadMe.
