### ISSUE TITLE
Should Dismiss on tap outside AlertView

### ISSUE THREAD

**Issue by Dev-** [vikmeup/SCLAlertView-Swift#156]
The following functionality is supported on the Objective-C version of SCLAlertView:

`shouldDismissOnTapOutside = YES;`

Tapping the dimmed screen dismisses the Alert View. 

Would be great if this could be brought over to the Swift version.

**Comment by blazierkyle** [comment]
In the Swift version this is called "hideWhenBackgroundViewIsTapped"

**Comment by Dev-** [comment]
Thanks for your response. 

That property is not in the version that gets pulled down from CocoaPods. 

i.e. pod 'SCLAlertView', '~> 0.5' or  pod 'SCLAlertView' as per the README. 

However I do see it when I download the ZIP and run the Example project.

**Comment by vikmeup** [comment]
Podspec updated now.

**Comment by WrathChaos** [comment]
Hello, I could not use hideWhenBackgroundViewIsTapped function.. It is not working at all. Can you give me an example of its usage please?
