### ISSUE TITLE
2 (or more lines) of text on button?

### ISSUE THREAD

**Issue by craigpearce5** [vikmeup/SCLAlertView-Swift#158]
When the text for the buttons are too long, it truncates it all.  Is it possible to reduce the size of the font and go to 2 lines?

**Comment by vikmeup** [comment]
@craigpearce5  Feel free to send Pull Request

**Comment by sdbarron** [comment]
If anyone implements this, could I request/suggest that it be an Option.  I wouldn't want the font size to get unreadable when the filename is long.  I bet we could get two lines _without_ making the font smaller.

**Comment by craigpearce5** [comment]
I'm still pretty new at swift, but I'm guessing it would be accomplished by adding some code here.

    private func addButton(title:String)->SCLButton {
        // Update view height
        kWindowHeight += kButtonHeight
        // Add button
        let btn = SCLButton()
        btn.layer.masksToBounds = true
        btn.setTitle(title, forState: .Normal)
        btn.titleLabel?.font = UIFont(name:kButtonFont, size: 14)
        contentView.addSubview(btn)
        buttons.append(btn)
        return btn
    }

Perhaps `btn.titleLabel?.numberOfLines = 2`?

Don't have my mbp with me otherwise I would test that.
