### ISSUE TITLE
Now Is it Support Carthage? 

### ISSUE THREAD

**Issue by yoohoogun114** [vikmeup/SCLAlertView-Swift#159]
Now, I Added In Cartfile with 
```
github "vikmeup/SCLAlertView-Swift"
```

But When I Run With 
```
carthage update SCLAlertView-Swift
```

Then

```
*** Skipped building SCLAlertView-Swift due to the error:
Dependency "SCLAlertView-Swift" has no shared framework schemes
```

**Comment by vikmeup** [comment]
SCLAlertView.xcodeproj has shared scheme framework. Not sure what the problem is.

**Comment by jgao1** [comment]
Same problem here. Was trying to include "SCLAlertView-Swift" in my project through Carthage.

**Comment by hibento** [comment]
Work's fine for me - with latest carthage version and current master.

**Comment by vikmeup** [comment]
@hibento Thanks!

**Comment by Damnum** [comment]
The problem is this old tag 0.22: https://github.com/vikmeup/SCLAlertView-Swift/tree/0.22

Carthage takes this as the newest version. This tag should be probably renamed or deleted.

github "vikmeup/SCLAlertView-Swift" ~> 0.5.9

works

**Comment by algrid** [comment]
I just removed the 0.22 tag.
