### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by iThanh** [vikmeup/SCLAlertView-Swift#162]
When i call:
SCLAlertView().showError("Error", subTitle: "Please contact Administrator.")

My ViewController error in:
let rv = UIApplication.sharedApplication().keyWindow! as UIWindow

Please!

**Comment by vikmeup** [comment]
Do you call this on `viewDidLoad`? 
Try on `viewWillAppear`

**Comment by iThanh** [comment]
Thank you!

**Comment by TarangKhanna** [comment]
Having this problem even for a simple: 

SCLAlertView().showInfo("Important info", subTitle: "You are great")

I tried it in viewDidLoad, viewWillAppear, I have used this library for a year without any problems, 
Deployment target is: 9.3 with Xcode version 7.3
