### ISSUE TITLE
UIAutomation

### ISSUE THREAD

**Issue by fulldecent** [vikmeup/SCLAlertView-Swift#169]
I am using fastlane/snapshot to do automation for screenshots in multiple locales.

How do I click the "OK" button in a language-independent way using UI testing?

**Comment by vikmeup** [comment]
is there a way to target uibutton with view index or tag ?

**Comment by fulldecent** [comment]
The usual approach is to set an accessibility identifier

**Comment by fulldecent** [comment]
OK, resolved, I added this in storyboard:

    <accessibility key="accessibilityConfiguration" identifier="showSecretWord"/>

And then in the test:

    let showSecretWordButton = app.buttons["showSecretWord"]
    showSecretWordButton.tap()
    snapshot("03Secret")
