### ISSUE TITLE
SCLAlertView Custom Subview

### ISSUE THREAD

**Issue by mohsinka** [vikmeup/SCLAlertView-Swift#174]
@alec-c4 
First off, Thank you for this amazing Alert!! However, as prescribed in the "Readme" file;
```
// Add the subview to the alert's UI property
alert.customSubview = subview
```

The customSubview property of SCLAlertView is missing / wrongly removed from the current revision, or I am not understanding it properly. Please direct me towards the rightful implementation.

**Comment by vikmeup** [comment]
`public var customSubview : UIView?` there is customView property

**Comment by mohsinka** [comment]
Can you please refer to _line number_ where this is mentioned? I cannot find it anywhere in **SCLAlertView.swift**

**Comment by vikmeup** [comment]
Please refer to https://github.com/vikmeup/SCLAlertView-Swift#use-a-custom-subview-instead-of-a-subtitle
