### ISSUE TITLE
Instance property "appearance" is not public

### ISSUE THREAD

**Issue by zeusent** [vikmeup/SCLAlertView-Swift#179]
The new `appearance` variable is not public, thus making the need to explicitly set it on init instead of giving the option to later change it. Is that on purpose?

I would have expected to be able to do something like this

    let alertView = SCLAlertView()
    alertView.appearance.showCloseButton = false

But that doesn't work and instead I have to do this:

    let alertView = SCLAlertView(appearance: SCLAlertView.SCLAppearance(showCloseButton: false))

which feels cumbersome.

**Comment by vikmeup** [comment]
`SCLAlertView.SCLAppearance` is exposed for use. Current implementation render that have set to `appearance` property. 

```swift
let appearance = SCLAlertView.SCLAppearance(
    showCloseButton: false
)
let alertView = SCLAlertView(appearance: appearance)
alertView.showSuccess("No button", subTitle: "You will have hard times trying to close me")
```

That's the right way to use it.

**Comment by d4kr** [comment]
Hi, with SCLAlertView 0.5.6 implemented with cocoapods 1.0 the code

`let appearance = SCLAlertView.SCLAppearance(
    showCloseButton: false
)`

give me the following error

`Type SCLAlertView has no member SCLAppearance`

Any idea why?

thx, dk

**Comment by vikmeup** [comment]
@d4kr can you try it again? let me know

**Comment by ossmalpha** [comment]
It is not working, I'm getting the same error saying that there is no member `SCLAppearance`. I checked the .swift file for SCLAlertView pod and I can see `public struct SCLAppearance`, but, for some reason, this is not recognised in my project classes.

**Comment by ossmalpha** [comment]
@vikmeup And I tried reinstalling the pod, cleaning the project, relaunching Xcode, restarting my Mac and all the other tricks, but no result. :/

**Comment by vikmeup** [comment]
@ossmalpha have you tried Example Project?

**Comment by devJoshLopez** [comment]
anyone able to fix the Type SCLAlertView has no member SCLAppearance error? I just started getting it now too in a new project.
