### ISSUE TITLE
showCircularIcon and showCloseButton not working anymore

### ISSUE THREAD

**Issue by HowardTheDuck007** [vikmeup/SCLAlertView-Swift#194]
Hi, It appears that with new version the:

showCircularIcon and 
showCloseButton boolean properties 

are not working anymore. Alert says SCAlertView has no members with those names.

Am I doing anything wrong?  Thank you!

**Comment by devJoshLopez** [comment]
im getting the same

**Comment by HowardTheDuck007** [comment]
ops...it was indeed my mistake. You just need to use the appearance setting such as:

let appearance = SCLAlertView.SCLAppearance(showCloseButton: false, showCircularIcon: true)
        let alertView = SCLAlertView(appearance: appearance)
