### ISSUE TITLE
SCLAlerView Installation Error

### ISSUE THREAD

**Issue by Stephanehk** [vikmeup/SCLAlertView-Swift#199]
For some reason after installing SCLAlerView, when I run the xcode workspace 32 errors appear (they are all errors in the Podfile). I think this is an error with your pod since this does not happen for any other pods. May you please help me. Thanks.

**Comment by filmhomage** [comment]
#198 merged PR may cause pod install error.

@vikmeup 
Please push 0.5.9 tag and release.

**Comment by vikmeup** [comment]
Done
`- June 15th, 16:36: Push for `SCLAlertView 0.5.9' initiated.`

**Comment by Stephanehk** [comment]
What does this mean?
