### ISSUE TITLE
Instanciation of SCLAlertView or SCLAlertView.SCLappearance only with all or zero parameters possible

### ISSUE THREAD

**Issue by mkayswork** [vikmeup/SCLAlertView-Swift#202]
Hey,

I was trying to make a appearance for an AlertView. But when I want to make an instance with only several values, Xcode doesn't find them!

Example:
let appeareance = SCLAlertView.SCLAppearance(
    kButtonHeight = 45
)

Any solutions for that ? I imported the module in my .swift file and added the project via CocoaPods

**Comment by vikmeup** [comment]
`let appeareance = SCLAlertView.SCLAppearance(kButtonHeight: 45.0)`

try this way. This property names has to be renamed in the future for clarity.

**Comment by mkayswork** [comment]
Ah, it was ":" instead of "=", haven't noticed that... thank you! 😊
