### ISSUE TITLE
how to change  button border color??

### ISSUE THREAD

**Issue by shindonghyeok** [vikmeup/SCLAlertView-Swift#203]
hello i 'd like to change button's border color. i mean that i can change a button's background color. but  what i want is that changing button's border color. for example, background color is white and border color is blue... somthing like this... how can i do this??? please help me... 

ps : and also icon background border color...

**Comment by shindonghyeok** [comment]
//circleView.backgroundColor = viewColor  //original code
        circleView.layer.borderWidth = 1.0
        circleView.layer.borderColor = viewColor.CGColor

i can change circle view border color !

**Comment by askari01** [comment]
check SCLAlertView.swift file in pods

**Comment by appaiahnb** [comment]
Any leads on changing border color for buttons ?

**Comment by plarsson** [comment]
let btn = alertView.addButton(... 
btn.layer.borderColor = UIColor.white.cgColor
btn.layer.borderWidth = 1.0
