### ISSUE TITLE
Delay dismissing the alert view 

### ISSUE THREAD

**Issue by ChenCodes** [vikmeup/SCLAlertView-Swift#212]
Hello! I'm trying to figure out how I can delay the dismissal of the alertview. So basically when I enter in some text into a uitextfield and then press Confirm, I want to dismiss the alertview only if the text they entered matches some default text. Right now when I press on the confirm button it dismisses the alertview regardless of what I put in the textfield. Any help would be greatly appreciated!

**Comment by vikmeup** [comment]
@ChenCodes if you set `shouldAutoDismiss` property then you will have control over it.

**Comment by ChenCodes** [comment]
@vikmeup Yeah so I tried that but my button disappears after I press on it.

**Comment by ChenCodes** [comment]
Here is my code for reference:

let appearance = SCLAlertView.SCLAppearance(
        showCircularIcon: true,
        showCloseButton: false,
        shouldAutoDismiss: false
    )
    var validity = false

    func clickMe(sender: UIButton!) {
        let alertView = SCLAlertView(appearance: appearance)
        let alertViewIcon = UIImage(named: "caughtIcon") //Replace the IconImage text with the image name
        let txt = alertView.addTextField("Name")
        txt.autocorrectionType = .No
        
        alertView.addButton("Confirm") {
            if self.validity == true {
                alertView.showWarning("", subTitle: "", duration: 1)
            } else {
//Nothing should happen here, alertview stays active. 
        }
        
        alertView.showInfo("Congratulations!", subTitle: "What did you catch?", circleIconImage: alertViewIcon)
    }

**Comment by ChenCodes** [comment]
Figured it out:
Just needed to set the color of my button
alertView.addButton("OK", backgroundColor : UIColor.greenColor() // for example )
