### ISSUE TITLE
Instant Synchronization

### ISSUE THREAD

**Issue by SketchySwift** [vikmeup/SCLAlertView-Swift#214]
Hi, I am having a problem reloading some tableview's data.
![simulator screen shot jul 16 2016 10 14 49 pm copy](https://cloud.githubusercontent.com/assets/15222571/16898331/fd9d5b88-4ba2-11e6-8b77-8405018bafa6.png)
Here is my app - to-do-list. I am allowing the user to add task, so when he/she adds a task the task doesn't show right away. But when I go to another view and come back, it will be there. I have tried this with the apple's alert controller view, and it works. It shows the task right away, but with SCLAlertView, it only happens when I re-load the view.

**Comment by sarfrazb** [comment]
perhaps put self.tableView.reloadData() into the method that is called when the user taps "Add"?

**Comment by HardcoreIOS** [comment]
@sarfrazb Still doesn't work

**Comment by algrid** [comment]
That’s probably not related to the library itself.
