### ISSUE TITLE
Silly question about default Done button

### ISSUE THREAD

**Issue by SamuelShaw** [vikmeup/SCLAlertView-Swift#228]
Hello I understand the done button dismisses the view.. Is there a way to remove that button or is it there to stay? :) thank you!

**Comment by SamuelShaw** [comment]
Thanks to your wonderful doc I was able to see it! (closeButton title) Please close this issue when you can! :)

**Comment by ispha** [comment]
I could do this following their documentation by making an appearance style for the Alert then assigning it to my alert . It works perfectly .

let appearance = SCLAlertView.SCLAppearance(

        showCloseButton: false
    )
let alertView = SCLAlertView(appearance: appearance)
