### ISSUE TITLE
Xcode 8 and Swift 3

### ISSUE THREAD

**Issue by ricgreenfield** [vikmeup/SCLAlertView-Swift#233]
Hi everyone, please any update for Xcode 8 and swift 3?. I try to instal the 0.6.0 version but seems to be no existing yet.
Thanks

**Comment by ricgreenfield** [comment]
So, installed the 0.6.0 but now 2 issues when transform to swift 3 at SCLAlertView.swift at lines 501 and 554

**Comment by vikmeup** [comment]
Swift 3.0 compatible version up on master.
