### ISSUE TITLE
Xcode 8 and swift 3

### ISSUE THREAD

**Issue by luka1995** [vikmeup/SCLAlertView-Swift#234]
Hi,

I can't use showCloseButton in SCLAlertView.SCLAppearance.

let appearance = SCLAlertView.SCLAppearance(
                    kTitleFont: ACFont.fontMediumWithSize(16),
                    kTextFont: ACFont.fontRegularWithSize(14),
                    kButtonFont: ACFont.fontRegularWithSize(15),
                    contentViewColor: UIColor.white,
                    showCloseButton: false
                )

It says "Cannot invoke value" etc...

?

**Comment by ricgreenfield** [comment]
Hi luka1995, how can you resolve the 2 issues when transform to swift 3? I have the two issues at line 501 and 554 of SCLAlertViews.swift.
Thanks

**Comment by johnlev** [comment]
I have the same issues. +1

**Comment by Lengo46** [comment]
+1

**Comment by meismyles** [comment]
+1

**Comment by edelibasi** [comment]
+1

**Comment by meismyles** [comment]
Surely we can't be the only few people having this issue? Seems like struct initializers no longer allow you to skip parameters that have default parameters set?

**Comment by joe528** [comment]
+1, how did you guy fix this?

**Comment by meismyles** [comment]
@joe528  I didn't. I stopped using the library and started using a different alert library.

**Comment by Lengo46** [comment]
@joe528, i've altered SCLAlertView.swift manually (line 160+) to have my own styling as a work around.This doesn't work if you want different stying on different alerts.

**Comment by cdepace** [comment]
Do you know when it will be compatible with Swift3?

**Comment by vikmeup** [comment]
@cdepace just published `0.7.0` with support for swift 3

**Comment by ninoguba** [comment]
@vikmeup thanks for supporting Swift 3 but I think this issue is still open.   Before we can SCLAppearance() with only the parameters we are customizing but now in Swift 3 it wont even compile complaining about missing parameters.

**Comment by ghohh** [comment]
this issue is still present

**Comment by maksamster** [comment]
![image](https://user-images.githubusercontent.com/13431668/27855222-38691ada-619c-11e7-8652-40ca68577a6d.png)
Can you help me? tsk

**Comment by maksamster** [comment]
![image](https://user-images.githubusercontent.com/13431668/27855264-6a3de2f2-619c-11e7-97b7-eb70aac60778.png)

Can you help me? this is optional.

**Comment by johnlev** [comment]
You’re gonna need to unwrap those strings. Currently you are generating a strong using two optional values. I assume you are using swift, so if you are confident that they will have values you can unwrap them by using the ! like so:

let string = “\(myVariable!)”

Another option if you aren’t sure if the value will be nil or not, you can unwrap it using a value to default to if it is nil using the ?? operator like so:

let string = “\(myVariable ?? “Default value”)”

Another option is to do conditional unwrapping, using the if let syntax. This will attempt to unwrap the variable:

var string = “”
if let value = myVariable {
    // value is now unwrapped
    string = value
} else {
    // myVariable was nil
    string = “Default value”
}

Last option: use a guard statement to exit the function if it is nil:

guard let string = myVariable else {
   return
}

**Comment by maksamster** [comment]
func showInfoMessage(info: String, subTitle: String, closeTitle: String,duration: TimeInterval) {
    
        let appearance = SCLAlertView.SCLAppearance(
        showCloseButton: false
        )
        
        let alert = SCLAlertView(appearance: appearance)
        alert.addButton("拨打电话") { 
            
            let telStr = CCUserAccountModel.sharedInstance.account!.serverMobile
            UIApplication.shared.openURL(URL(string: "telprompt://\(telStr ?? "")")!)
        }
        alert.addButton("人工查询", target: self, selector: #selector(personHelp))
        
        alert.addButton("关闭", backgroundColor: UIColor(hexColor: "c7c7c7"), textColor: UIColor(hexColor: "717171"), showDurationStatus: true) {
            
        }
        alert.showInfo(info, subTitle: subTitle, duration: duration, colorStyle: 0x1f6aa7, animationStyle: .noAnimation)

    }

@johnlev  this is optional,don’t need to unwrap those strings
