### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by ossmalpha** [vikmeup/SCLAlertView-Swift#236]
When is this going to be updated for Swift 3 and merged in master?

**Comment by RemyDCF** [comment]
The Swift 3 Version is already merged to master branch ( #235 )

**Comment by jvmk** [comment]
@RemyDCF When installing through cocoapods, you still get a Swift 2.x version that Xcode 8 offers to convert. It's version number is 0.6.0. I tried deleting the cocoapods cache, but unfortunately that didn't help. Any ideas?

**Comment by jvmk** [comment]
A temporary workaround is to point to the master branch:
`pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift'`

**Comment by vikmeup** [comment]
I will update pod spec tonight. But for now you can use @jvmk workaround.

**Comment by eman6576** [comment]
Make sure that the pod target's `Use Legacy Swift Language Version` is set to `NO` after doing @jvmk 's workaround.

**Comment by ricgreenfield** [comment]
Use @jvmk (pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift') don't work. Xcode ask to convert to latest Swift 3 syntax

**Comment by jvmk** [comment]
@ricgreenfield just go ahead and let xcode do that. You should see that it finds that no source code changes are needed and that you only need to update the Swift version of the project.

**Comment by ricgreenfield** [comment]
Thanks @jvmk. Works

**Comment by zeusent** [comment]
@vikmeup is this going to take long now? I think an easy `Podspec` update would fix this once and for all. Is there something specific you are waiting for?

**Comment by wangbourne** [comment]
@RemyDCF , the latest version on pod is 0.6.0, which is not for 3.0

I think it's only for a temp solution: Use @jvmk (pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift') 

so it's better to update pod again

thanks

**Comment by zeusent** [comment]
Why isn't the Swift 3 version a new release already? @vikmeup ?

**Comment by Nonchalant** [comment]
Please new release version including Swift 3 verstion @vikmeup

**Comment by vikmeup** [comment]
Will do tonight

**Comment by vikmeup** [comment]
Updated. Latest version `0.7`

**Comment by alexvazquez** [comment]
Hi, what is the version that I need to target so It still working with Swift 2.3? Thanks

**Comment by RemyDCF** [comment]
You can use the swift-2.3 branch.
