### ISSUE TITLE
Custom UIImage To Fill CircleIcon

### ISSUE THREAD

**Issue by sarfrazb** [vikmeup/SCLAlertView-Swift#248]
Hi

When I use a custom icon in place of the default icons, it seems to only take up a small part of the icon (see image below).
This is regardless of the size of source image. I've tested with 64x64, as well as 512x512 and it has the same result.
Can anyone provide some assistance as to what I might be doing wrong?

Thank you :)

![image](https://cloud.githubusercontent.com/assets/13691330/19024278/228d551a-894c-11e6-8cbe-d45d9acb1469.png)

**Comment by fishfisher** [comment]
You can change the icon size with the folowing:

`let appearance = SCLAlertView.SCLAppearance(
            kCircleIconHeight: 55.0,
            showCircularIcon: true
        )`

This gives you an icon size of 55x55. You can see in the public init SCLAppearance that  the kCircleIconHeight: CGFloat = 20.0 and the circle surrounding it is kCircleHeight: CGFloat = 56.0.
