### ISSUE TITLE
Delete old tag 0.22

### ISSUE THREAD

**Issue by Damnum** [vikmeup/SCLAlertView-Swift#249]
Trying to get the newest version of `SCLAlertView-Swift` with Carthage like this:

`github "vikmeup/SCLAlertView-Swift"`

This fails because Carthage thinks the latest version is 0.22 because of the 2 years old tag.

Solution would be to delete the old tag (or rename).

**Comment by fever324** [comment]
Please remove [tag 0.22](https://github.com/vikmeup/SCLAlertView-Swift/releases/tag/0.22)

**Comment by algrid** [comment]
removed the tag
