### ISSUE TITLE
300+ issues preventing compilation

### ISSUE THREAD

**Issue by dnewberr** [vikmeup/SCLAlertView-Swift#257]
Hello,

When trying to add via cocoapods, I seem to run into strange issues that  (as far as I can tell) no one else really does. Here's an example:
![screen shot 2016-10-24 at 1 28 21 pm](https://cloud.githubusercontent.com/assets/5789176/19662746/c4b70078-99ed-11e6-8193-11e80d4ab38b.png)
Any advice?

**Comment by AndreasDpp** [comment]
If you are using swift 3, you can 
<img width="479" alt="skaermbillede 2016-10-26 kl 21 21 39" src="https://cloud.githubusercontent.com/assets/7473973/19741742/35bb08b6-9bc2-11e6-9077-69a79ec8e16c.png">

**Comment by BethKnight1234** [comment]
I'm having the same problem, but I don't have a SideMenu in my project. Is it something I need to add?

**Comment by AndreasDpp** [comment]
No its just another liberary/framework.


2016-11-03 2:02 GMT+01:00 Beth Knight <notifications@github.com>:
