### ISSUE TITLE
Swift 3 issue even with version 0.7

### ISSUE THREAD

**Issue by gyrotechnologies** [vikmeup/SCLAlertView-Swift#264]
I have update the framework to the latest version(i.e. 0.7). Despite this Xcode 8 still asks to convert to the latest version of swift. If I ask to convert later Xcode throws the error : 
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

Any ideas what the problem could be?

**Comment by Dev-** [comment]
I had this problem as well. 

Switched to SCLAlert 0.5 with Swift 2.3 on Xcode 8.1 with no issues now though.

**Comment by gyrotechnologies** [comment]
I managed to love the problem to updating to the latest version of cocoa pods(1.1.1). With this version I was able to use SCLAlertView 0.7
