### ISSUE TITLE
value of type 'String' has no member heightWithConstrainedWidth

### ISSUE THREAD

**Issue by simonnarang** [vikmeup/SCLAlertView-Swift#266]
![screen shot 2016-11-16 at 5 26 47 pm](https://cloud.githubusercontent.com/assets/9156815/20368425/ea04d008-ac21-11e6-9a90-6340bc549760.png)

Can someone help me figure out what's going on?

**Comment by simonnarang** [comment]
This is within SCAlertView.swift

**Comment by EstefaniaGilVaquero** [comment]
Hi simnonnarang, how did you fix this? i have the same problem.

Thanks!

**Comment by tahseen0amin** [comment]
For Anyone who is still struggling with this issue

This method is in the SCLExtension.swift. Import this file as well.
