### ISSUE TITLE
Prevent from close when button is tapped

### ISSUE THREAD

**Issue by Sumeet21** [vikmeup/SCLAlertView-Swift#277]
when using text field
alert.showEdit("title", subTitle: "This alert view shows a text box")

if text field is empty i don't want to close dialog and show user a message that 'please enter text',
how to prevent from close when dialog button is clicked?

**Comment by Sumeet21** [comment]
i have modified source code just commit sideview() in buttonTapped(_) method 

```
func buttonTapped(_ btn:SCLButton) {
        if btn.actionType == SCLActionType.closure {
            btn.action()
        } else if btn.actionType == SCLActionType.selector {
            let ctrl = UIControl()
            ctrl.sendAction(btn.selector, to:btn.target, for:nil)
        } else {
            print("Unknow action type for button")
        }
        
        if(self.view.alpha != 0.0 && appearance.shouldAutoDismiss)
        {
        //    hideView()
        }

    }

```

**Comment by YoannLth** [comment]
Hi, I faced the same problem and I resolved it differently.

You can just set "shouldAutoDismiss" in appearance and then, manually dismiss the alert.
Maybe it will not be helpful for you, but it can be for others ;)

````
let appearance = SCLAlertView.SCLAppearance(
            shouldAutoDismiss: false
)
let alert = SCLAlertView(appearance: appearance)
alert.addButton("Keep open") {
      // Your code here
}
alert.addButton("Close") {
    alert.hideView()
}
alert.showEdit("Title", subTitle: "subTitle")
````

**Comment by anushkmittal** [comment]
@YoannLth yes, this helped me! Thanks for sharing 😊
