### ISSUE TITLE
Compile Error for Swift

### ISSUE THREAD

**Issue by NitWitStudios** [vikmeup/SCLAlertView-Swift#28]
I attempted to install this library as a pod, and get these errors right away when compiling
![screen shot 2014-10-20 at 12 20 39 pm](https://cloud.githubusercontent.com/assets/1779541/4707531/813e5960-588e-11e4-98ba-c8a841142049.png)

**Comment by Rameshv** [comment]
@vikmeup still its not resolved. But there seems to be a workaround according to the post https://github.com/CocoaPods/CocoaPods/issues/2226#issuecomment-55279647 

As per the post

```
It works with Xcode 5 command line tools. Make sure that Xcode command line tools version is set to 5.x.x.

Xcode preference > Location tab > Command Line Tools

**Comment by vikmeup** [comment]
@Rameshv I wish I had Xcode 5 installed.

**Comment by Rameshv** [comment]
@vikmeup oops thats a bummer :(

**Comment by Rogog** [comment]
Had the same issue as original comment on xcode 6.1.1, latest Cocoapod, tried to copy the file over and that failed also.

**Comment by MHaroonBaig** [comment]
I think you should release it via Cocoa Pods beta. It started supporting Swift as of now.

**Comment by Rogog** [comment]
Tried with Cocoa Pods beta which alledgly does support swift.  The alert is still not working.  Any advice?

**Comment by bbdevelopment** [comment]
I would like to get an update on this as well.  would really like to use this in my current project but getting the above errors.  I am using the pod beta and have no problems with any of the other swift installs.

**Comment by AnthonyMDev** [comment]
These are just some issues with changes to the Swift syntax with Swift 1.1.

Its incredibly easy to fix. @vikmeup, would you like me to submit a pul request, or is this getting done soon?

**Comment by vikpower** [comment]
@AntonyMDev, please do! Thanks

**Comment by AnthonyMDev** [comment]
@vikmeup , @vikpower 
Actually, after forking the repo, I realized that the problems have been fixed, you just need to push a new version with the fixes up to the CocoaPods Master Repo.

Do you need help with that, or can you get that taken care of?

**Comment by vikmeup** [comment]
@AnthonyMDev I would push it tonight, but if you have chance, please do! Thanks.

**Comment by AnthonyMDev** [comment]
Well, I don't have the credentials to push to your Pod Trunk, so you have to do it. Just wanted to make sure you knew the process.

**Comment by vikmeup** [comment]
@AnthonyMDev could you check if it works now? I updated podspec for version 0.3.1 and did `pod truck push`

**Comment by isair** [comment]
@vikmeup Could you push the latest podspec file as well? 0.4 isn't available through Cocoapods.

**Comment by vikmeup** [comment]
@isair Thanks. Just pushed it!
