### ISSUE TITLE
Not compatible with Swift 3

### ISSUE THREAD

**Issue by ghost** [vikmeup/SCLAlertView-Swift#284]
This code is not compatible for Swift 3..

Can anyone convert the code so it's compatible with Swift 3?

Edit: **Here you can find the Swift 3 source code: https://github.com/vikmeup/SCLAlertView-Swift/releases/tag/0.7.0 :)**

**Comment by jVirus** [comment]
The issue should be closed since `0.7.0` version is fully compatible with `Swift 3`
