### ISSUE TITLE
Why is the custom icon cropped to a circle?

### ISSUE THREAD

**Issue by Sweeper777** [vikmeup/SCLAlertView-Swift#296]
This is the image I want to use as the icon. It has a transparent background but because it's all white Xcode shows it as having a grey background.

<img width="76" alt="screen shot 2017-02-18 at 8 50 34 am" src="https://cloud.githubusercontent.com/assets/13585047/23091887/d2c42dd2-f5b7-11e6-9da5-8510643fe789.png">

This is how it looks in the alert view:

<img width="74" alt="screen shot 2017-02-18 at 8 49 59 am" src="https://cloud.githubusercontent.com/assets/13585047/23091895/fcd6c1a2-f5b7-11e6-83d4-d5ce155d5727.png">

As you can see, it is cropped. Only part of the "+" sign is shown. Can you make it not crop the image? There are a lot of empty space so just show the full image!

**Comment by radudominte** [comment]
I have the same problem, anyone knows how to fix this issue?

**Comment by appaiahnb** [comment]
i suggest you to comment this 
"circleIconView?.layer.cornerRadius = circleIconView!.bounds.height / 2"

**Comment by Sweeper777** [comment]
Which line is that? Can you tell me the line number?

**Comment by appaiahnb** [comment]
Line number can differs, check this Function name below.

// showTitle(view, title, subTitle, duration, style)
open func showTitle(_ title: String, subTitle: String, duration: TimeInterval?, completeText: String?, style: SCLAlertViewStyle, colorStyle: UInt?=0x000000, colorTextButton: UInt?=0xFFFFFF, circleIconImage: UIImage? = nil, animationStyle: SCLAnimationStyle = .topToBottom) -> SCLAlertViewResponder  {
 }

**Comment by Sweeper777** [comment]
It was line 708 on mine as well 😄 . The solution worked. Thank you!

**Comment by appaiahnb** [comment]
@Sweeper777 Hi , can you reopen the same? So that we can send fix.

**Comment by appaiahnb** [comment]
https://github.com/vikmeup/SCLAlertView-Swift/pull/338
