### ISSUE TITLE
Don't show empty space if title is empty.

### ISSUE THREAD

**Issue by Sweeper777** [vikmeup/SCLAlertView-Swift#300]
I use this code to show an alert:

    let alert = SCLAlertView(appearance: SCLAlertView.SCLAppearance(showCloseButton: false, showCircularIcon: false))
    alert.addButton("OK", action: {})
    _ = alert.showCustom("", subTitle: "Some text", color: UIColor(hex: "5abb5a"), icon: UIImage(color: nil))

The alert shown has a lot of empty space above "Some text". It looks kind of bad IMO. It would be nice if the alert's size becomes smaller if the title is empty.

**Comment by algrid** [comment]
Is this problem still present in the latest version? I can't reproduce it.

**Comment by Sweeper777** [comment]
I will try to reproduce it tomorrow after I updated the pod!

**Comment by Sweeper777** [comment]
I can still see a lot of whitespace:

<img width="234" alt="2017-06-12 7 38 26" src="https://user-images.githubusercontent.com/13585047/27021745-4be80d8a-4f42-11e7-893e-86d043000cf4.png">

**Comment by algrid** [comment]
@Sweeper777 I see now - the problem is present in the current pod version(0.7.0). In master branch it's fixed.
