### ISSUE TITLE
App crashes after alert appears twice

### ISSUE THREAD

**Issue by BrandonMayU** [vikmeup/SCLAlertView-Swift#309]
If I get an error the alert view pops up and everything is fine, then if I get an error again in the app i present the .showError, however, when someone dismisses the alert the app crashes. This only happens the second time they dismiss the app. Any solutions?

**Comment by crystalSETH** [comment]
When `func hideView` is called, some clean up happens and all buttons' `action`, `target`, and `selector` attributes are set to `nil`. I had to comment out those lines that were setting these values to `nil`. Hope this helps.
