### ISSUE TITLE
Localize the text?

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [vikmeup/SCLAlertView-Swift#315]
I found that it is hard to localize the text in the alert.
Like the text "Done" in Error alert,I have no way to edit it.

**Comment by ghohh** [comment]
just use the the method showerror with close buton option

`alert.showError("opps", subTitle: "there is an issue", closeButtonTitle: "ok")
`

**Comment by CaptainYukinoshitaHachiman** [comment]
OK,I got it.
Thx
