### ISSUE TITLE
Using TableViewCell as Subview

### ISSUE THREAD

**Issue by sarfrazb** [vikmeup/SCLAlertView-Swift#341]
Hi, 

I use Storyboards, and I have a prototype cell defined in a TableView. It's a header cell that summarises the rest of the table.

I am wanting to use this prototype cell as the subview of a SCLAlertView, i.e. so that it shows the summary of the table on the view underneath the alertView.

I tried using:

``` swift
let cell = tableView.dequeueReusableCell(withIdentifier: "header") as! PayHeaderTVC
```
and then modifying the cell's properties:
```swift
        cell.lblItemsMarked.text = "\(itemsMarkedCount)"
        cell.lblTotalMarking.text = markingTotal.Currency()
```

and then finally calling `alertView.customSubview = cell`, but when the alertView shows, the subview does not.

Any ideas?

Cheers
Saf

**Comment by algrid** [comment]
UITableViewCell is not supposed to be used outside of UITableView. You can create your own custom view and use it as a subview of your cell's contentView and as `alertView.customSubview` (not the same instance of course, two different instances).
