### ISSUE TITLE
Please make updates to pod for Swift 4

### ISSUE THREAD

**Issue by tidyware** [vikmeup/SCLAlertView-Swift#351]
Swift 4 brings new requirements and changes to the language that can be implemented in a backward compatible way.

Please update the source code to reflect the new requirements (for selectors, etc.) so it's ready to work with Swift 4.

**Comment by fullmetalsheep** [comment]
The current head in git works with Swift 4.
`pod 'SCLAlertView',:git => 'https://github.com/vikmeup/SCLAlertView-Swift.git'`
add above code to your cocoapods file instead of using `'SCLAlertView'`

**Comment by tidyware** [comment]
Got it. Thank you.

**Comment by mickychen0524** [comment]
@fullmetalsheep it looks like it's not fully updated for swift 4
SCLExtensions.swift:48:136: 'NSFontAttributeName' has been renamed to 'NSAttributedStringKey.font'
SCLAlertView.swift:759:25: 'NSFontAttributeName' has been renamed to 'NSAttributedStringKey.font'

**Comment by fullmetalsheep** [comment]
i will push a fix this weekend, im not with my macbook right now.

**Comment by mickychen0524** [comment]
@fullmetalsheep thanks, please update here when it's pushed
