### ISSUE TITLE
Close button not visible

### ISSUE THREAD

**Issue by nitishrana28** [vikmeup/SCLAlertView-Swift#353]
This is my code. And attached is the screenshot  
  
```
 let appearance = SCLAlertView.SCLAppearance(
            kTitleFont: UIFont(name: "Poppins", size: 20)!,
            kTextFont: UIFont(name: "Poppins", size: 14)!,
            kButtonFont: UIFont(name: "Poppins", size: 14)!,
            showCloseButton: true
        )
        
        let alert = SCLAlertView(appearance: appearance)
        
        alert.addTextField("Country")
        alert.addTextField("City")
        alert.addTextField("Street")
        
        
        alert.addButton("Get Location", backgroundColor: UIColor(red: 165.0/255.0, green: 11.0/255.0, blue: 39.0/255.0, alpha: 1.0), textColor: UIColor.white, showDurationStatus: false) {
            
        }
        
        alert.showTitle("Set your location", subTitle: "Enter your current location", style: .edit, closeButtonTitle: "Done", duration: 0, colorStyle: 0xb61f34, colorTextButton: 0xb61f34, circleIconImage: UIImage(named:"location.png"), animationStyle: SCLAnimationStyle.bottomToTop)
```  
  
![simulator screen shot 04-sep-2017 12 20 16 pm](https://user-images.githubusercontent.com/1484780/30014747-92596f6e-916b-11e7-8f04-032621ba707d.png)

**Comment by fullmetalsheep** [comment]
I cant figure out what went wrong with your code. Probably the text is the same colour as the background.But there's an alternative solution.Close button by default does nothing, therefore just create another dummy button with whatever the text you want.

`showCloseButton: false`

and then add

`alert.addButton("Close", backgroundColor: UIColor(red: 165.0/255.0, green: 11.0/255.0, blue: 39.0/255.0, alpha: 1.0), textColor: UIColor.white, showDurationStatus: false) {}`

after the other button. You don't have to code anything inside the function.

Didn't get a chance to check this, but it should work, i did something similar a few weeks back.

**Comment by nitishrana28** [comment]
Yup the text was having the same color as button. Closing the issue
