### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by jlaws** [vikmeup/SCLAlertView-Swift#358]
Any plans to update the library to support Swift 4?

**Comment by fabioiegri** [comment]
Hello. First of all, thank You for Your job.

........./Pods/SCLAlertView/SCLAlertView/SCLAlertView.swift:160:999: Global function 'UIColorFromRGB' is internal and cannot be referenced from a default argument value
I receive the following error:

Related code:
`public init(kDefaultShadowOpacity: CGFloat = 0.7, kCircleTopPosition: CGFloat = -12.0, kCircleBackgroundTopPosition: CGFloat = -15.0, kCircleHeight: CGFloat = 56.0, kCircleIconHeight: CGFloat = 20.0, kTitleTop:CGFloat = 30.0, kTitleHeight:CGFloat = 25.0, kWindowWidth: CGFloat = 240.0, kWindowHeight: CGFloat = 178.0, kTextHeight: CGFloat = 90.0, kTextFieldHeight: CGFloat = 45.0, kTextViewdHeight: CGFloat = 80.0, kButtonHeight: CGFloat = 45.0, kTitleFont: UIFont = UIFont.systemFont(ofSize: 20), kTextFont: UIFont = UIFont.systemFont(ofSize: 14), kButtonFont: UIFont = UIFont.boldSystemFont(ofSize: 14), showCloseButton: Bool = true, showCircularIcon: Bool = true, shouldAutoDismiss: Bool = true, contentViewCornerRadius: CGFloat = 5.0, fieldCornerRadius: CGFloat = 3.0, buttonCornerRadius: CGFloat = 3.0, hideWhenBackgroundViewIsTapped: Bool = false, contentViewColor: UIColor = UIColorFromRGB(0xFFFFFF), contentViewBorderColor: UIColor = UIColorFromRGB(0xCCCCCC), titleColor: UIColor = UIColorFromRGB(0x4D4D4D)) {
            `

and:
........./Pods/SCLAlertView/SCLAlertView/SCLAlertView.swift:549:192: Var 'defaultColorInt' is internal and cannot be referenced from a default argument value

Thank You very much
Have a nice day
Fabio

**Comment by ahmedsafadii** [comment]
<img width="790" alt="screen shot 2017-09-23 at 2 07 25 am" src="https://user-images.githubusercontent.com/6974081/30767277-fe5f6fdc-a003-11e7-8442-13924ffd0a34.png">

for now you have to do this ^_^

**Comment by vikmeup** [comment]
@jlaws feel free to submit PR, I would be happy to merge

**Comment by Coppola-Aleandro** [comment]
I have a same problem: 
Global function 'UIColorFromRGB' is internal and cannot be referenced from a default argument value
end other like:
Argument of '#selector' refers to instance method 'tapped' that is not exposed to Objective-C

**Comment by kuzdu** [comment]
I'm confused. I checked out the project and with Swift 4 the code is fine . 
When you call the pod like this `pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift', :branch => 'master'` you will getting a working Swift 4 version.

Only If you call `pod 'SCLAlertView'` or `pod 'SCLAlertView', '0.7.0'` it doesn't work. Is there another version to check out? 

Can we (or I) help to release a working version without checking out the master branch?

**Comment by UtkuDalmaz** [comment]
Can anyone please update this ????

**Comment by shaheero** [comment]
Using pod update didn't download the latest update (compatible with Swift 4). Download the files "`SCLAlertView.swift`" and "`SCLExtensions.swift`" from the GitHub repo here and replace them in `Pods/SCLAlertView`

**Comment by alijaza** [comment]
@vikmeup ☝️

**Comment by vikmeup** [comment]
Could you guys submit PR, I would be happy to merge!

**Comment by DavidLari** [comment]
@vikmeup: The code is already updated to Swift 4. No PR is needed. It's just that you haven't git tagged a new version and pushed to the pod trunk.

Until that is done, we can use the latest code with the following in our pod file:

```
pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git'
```

**Comment by yzhong52** [comment]
Any timeline for tagging a new version with official support for swift 4?

**Comment by avazquezpr** [comment]
@ahmedsafadii Thanks! Really helped.

**Comment by nmDejamobile** [comment]
Tagging and updating lib versions would be nice. Still in 0.7.0 but not compatible with swift 3.2 anymore. Still have a project to update to swift4 but it have to build before. So I had to point my podfile directly to 3687d7965630e58abae114c6544f9412c5e09b66

**Comment by vikmeup** [comment]
I will do tonight! Sorry guys for long delay.

**Comment by Ewg777** [comment]
@vikmeup better late than never

**Comment by jlaws** [comment]
@vikmeup how about tonight :)

**Comment by JamesHealdUK** [comment]
This would be awesome if possible!

**Comment by invisible66** [comment]
@vikmeup we are waiting "tonight" :D

**Comment by vikmeup** [comment]
Pushed! finally can close this!
