### ISSUE TITLE
Swift 4 

### ISSUE THREAD

**Issue by rayhk6** [vikmeup/SCLAlertView-Swift#359]
I used  #351  link for my project. However, the duration function is no longer work. Please kindly help to fix. Thanks.

**Comment by fullmetalsheep** [comment]
for now, click on the error. It should show automatically what the new code should look like. Then run the app again.

**Comment by rayhk6** [comment]
It doesn't support the duration now?
`alertView.showError("Title", subTitle:"abc", duration: 3)`
It shows 
Incorrect argument label in call (have '_:subTitle:duration:', expected '_:subTitle:closeButtonTitle:') Replace 'duration' with 'closeButtonTitle'

**Comment by fullmetalsheep** [comment]
hmm, i'm not with my macbook right now. I'll look into it this weekend. Hopefully someone else can do it sooner.

**Comment by justdan0227** [comment]
Please update.  Have always loved this library. Looking forward to Swift4 update

**Comment by ahmedsafadii** [comment]
I update the library for swift 4 



        pod 'SCLAlertView', :git => 'https://github.com/ahmedsafadii/SCLAlertView-Swift.git'

**Comment by rayhk6** [comment]
Thanks @ahmedsafadii , but not fixing the duration issue.

**Comment by ahmedsafadii** [comment]
@rayhk6 what issue , I used it and it's amazing oO

**Comment by ahmedsafadii** [comment]
try replace both file with this :)

**Comment by ahmedsafadii** [comment]
[Archive.zip](https://github.com/vikmeup/SCLAlertView-Swift/files/1336488/Archive.zip)

**Comment by Piyush08** [comment]
@ahmedsafadii I still facing same issue for duration!

**Comment by ahmedsafadii** [comment]
@Piyush08 can you share your code or screen the problem ?

**Comment by rayhk6** [comment]
@Piyush08  Please replace duration with timeout. It works for me.

**Comment by ahmedsafadii** [comment]
```
        let alert = SCLAlertView(appearance: appearance)
        let showTimeout = SCLButton.ShowTimeoutConfiguration(prefix: "(", suffix: " " + "second".localize() + ")")
        _ = alert.addButton("cancel_order".localize(), backgroundColor: UIColor(hex:"FFBA00"), textColor: UIColor.white, showTimeout: showTimeout) {

}

 let timeoutValue: TimeInterval = 5.0
        let timeoutAction: SCLAlertView.SCLTimeoutConfiguration.ActionType = {
            
            
        }
        
        alert.showWait("", subTitle: "order_message_to_drivers".localize(), timeout: SCLAlertView.SCLTimeoutConfiguration(timeoutValue: timeoutValue, timeoutAction: timeoutAction), colorStyle: 0xFFBA00, colorTextButton: 0xFFFFFF)
```

**Comment by Piyush08** [comment]
Hello @ahmedsafadii ,

Can't I use same format like as duration now? Just specify second & after that dismiss automatically.

Rather than this adding button scenario.

Thank you,

**Comment by rayhk6** [comment]
@Piyush08 
```
alertView.showInfo("", subTitle: "ABC", timeout: SCLAlertView.SCLTimeoutConfiguration(timeoutValue: 3, timeoutAction: SCLAlertView.SCLTimeoutConfiguration.ActionType = {
    print("")
}))
```

**Comment by Piyush08** [comment]
@ahmedsafadii 

still getting error as "Cannot assign to immutable expression of type 'SCLAlertView.SCLTimeoutConfiguration.ActionType.Type' (aka '(() -> ()).Type')"

**Comment by ahmedsafadii** [comment]
replace both file with this

https://github.com/vikmeup/SCLAlertView-Swift/files/1336488/Archive.zip

**Comment by Piyush08** [comment]
@ahmedsafadii I already replace this as you mentioned above

**Comment by ahmedsafadii** [comment]
@Piyush08 can you share the alert code here ^^"

**Comment by Piyush08** [comment]
![screen shot 2017-09-30 at 12 53 36 am](https://user-images.githubusercontent.com/7929845/31032513-dfb5aa3a-a579-11e7-914d-052681313e78.png)

**Comment by ahmedsafadii** [comment]
@Piyush08 the code please :3

**Comment by Piyush08** [comment]
@ahmedsafadii I already share as above image

**Comment by ahmedsafadii** [comment]
@Piyush08 ok give me a sec

**Comment by ahmedsafadii** [comment]
```
@Piyush08 

        let timeoutAction: SCLAlertView.SCLTimeoutConfiguration.ActionType = {
        // action here
        }
        
        SCLAlertView().showError("test", subTitle: "test",timeout:SCLAlertView.SCLTimeoutConfiguration(timeoutValue: 3.0, timeoutAction:timeoutAction))
```

**Comment by Piyush08** [comment]
@ahmedsafadii 

It works! 

Thanks for your quick & great help!

Happy coding!

**Comment by ahmedsafadii** [comment]
@Piyush08 np ;)

**Comment by justdan0227** [comment]
So whats the workflow for adding this to a new project now?

**Comment by vikmeup** [comment]
@justdan0227 create PR with changes to support Swift4, I would be happy to merge it

**Comment by ahmedsafadii** [comment]
@vikmeup https://github.com/vikmeup/SCLAlertView-Swift/pull/361
