### ISSUE TITLE
Memory leak every time custom alert is being presented

### ISSUE THREAD

**Issue by AndriyGo** [vikmeup/SCLAlertView-Swift#367]
Even in the original example clicking on the custom alert button causes a memory leak.

I couldn't yet locate a cause of it (hence lack of a PR). However, I think it is a serious issue which needs to be looked into.

**Comment by AndriyGo** [comment]
#368 should fix this issue

**Comment by pgawlowski** [comment]
Try to put this in 
`DispatchQueue.main.async { }`

there is a chance that you're triggering this from some sort of sub-thread - recently I run into this kind of issue.

If this is going to fix your problem please refer to this issue with some comment or support if you believe like me, that is supposed to be cover directly in SCLAlertView()

https://github.com/vikmeup/SCLAlertView-Swift/issues/377

**Comment by AndriyGo** [comment]
#381 fixes this for me. However, I do not fully understand why reassignment of appearance led to the memory leak in the first place.
