### ISSUE TITLE
The download version is 1.0,but the cocaPods is 0.7

### ISSUE THREAD

**Issue by youngsherlee** [vikmeup/SCLAlertView-Swift#374]
“buttonsLayout” is not support in 0.7

**Comment by youngsherlee** [comment]
“ buttonsLayout” is not support in 0.7

**Comment by fullmetalsheep** [comment]
cocoaPods is not updated for some reason. just use the master from git :)

**Comment by Ewg777** [comment]
@vikmeup any update on it?
