### ISSUE TITLE
SCLAlertView - show is probably not thread-safe

### ISSUE THREAD

**Issue by pgawlowski** [vikmeup/SCLAlertView-Swift#377]
Recently I run into situation when SCLAlertView was causing a lot of trouble, because it was triggered from inside one of sub-threads.

I was wondering why not to cover it directly in SCLAlert - cause UI supposed to handled always on main thread. 

So some sort of 
`DispatchQueue.main.async {}`
 
would be nice. 
What do you think about this kind of improvement?

**Comment by algrid** [comment]
Any UI code is expected to be called from the main thread. That's true for any UIKit stuff and it's also true for custom views. I don't think any special treatment is required here.
