### ISSUE TITLE
Please update version of .swift-version to 4.0

### ISSUE THREAD

**Issue by khanhshopback** [vikmeup/SCLAlertView-Swift#386]
Please update version of .swift-version to 4.0 and release new version for this.

**Comment by vikmeup** [comment]
I will try to do, pod was giving me errors.

**Comment by Rilu-Ril** [comment]
I am facing same issue

**Comment by vikmeup** [comment]
```
Viktors-iMac:SCLAlertView-Swift viktorradchenko$ pod trunk push

[!] Found podspec `SCLAlertView.podspec`
Updating spec repo `master`
Validating podspec
 -> SCLAlertView (0.8)

Updating spec repo `master`

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  SCLAlertView (0.8) successfully published
 📅  March 4th, 01:39
 🌎  https://cocoapods.org/pods/SCLAlertView
 👍  Tell your friends!
--------------------------------------------------------------------------------

```

**Comment by jerry1177** [comment]
Hi, ass soon as I install the pod and try to run the simple command: 

SCLAlertView().showInfo("Important info", subTitle: "You are great")

I get this error:
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

coming from the SCLAlertView.swift file. is there a fix for this bug?

**Comment by jerry1177** [comment]
Never mind this comment. I was calling it in the view did load method which gets called too early. great framework though!
