### ISSUE TITLE
Please update access levels...

### ISSUE THREAD

**Issue by seenoevo** [vikmeup/SCLAlertView-Swift#399]
I recently migrated from manual install of this library to using CocoaPods for easier future updates, and  I seem to have a lot of errors complaining about `protection level` and `unresolved identifier`:

![untitled](https://user-images.githubusercontent.com/8109158/38481064-c30c3648-3b7d-11e8-98b1-c54f87a77298.png)
![untitled2](https://user-images.githubusercontent.com/8109158/38481068-c55a6334-3b7d-11e8-9358-bfa739dd2a6f.png)

Yes I could modify the library code to fix this, but I rather not mess with it.

Can you please open up the access levels @vikmeup @Jerome1210 ?

**Comment by algrid** [comment]
AFAIK one isn't supposed to access those fields directly. For `showCloseButton` you can have:
```swift
let appearance = SCLAlertView.SCLAppearance(
    showCloseButton: false
)
```
Regarding that icon image - it's set automatically when you call `showError` if I'm not mistaken.

**Comment by seenoevo** [comment]
@algrid sorry for the late reply, I haven't gotten a chance to work on my project until recently.

1. How exactly is one suppose to use `showCloseButton` with the provided: 
```
let appearance = SCLAlertView.SCLAppearance(
    showCloseButton: false
)
```
2. That works for `showError`, but what about `showCustom`? Are users expected to provide their own icons now?
