### ISSUE TITLE
BAD_ACCESS on button tap

### ISSUE THREAD

**Issue by marcpages** [vikmeup/SCLAlertView-Swift#40]
Hi, I've opened your example project and when I tap any button it throws an exception `EXC_BAD_ACCESS` into `class AppDelegate: UIResponder, UIApplicationDelegate {`. What I am doing wrong?

Thanks.

**Comment by vikmeup** [comment]
What version of Xcode do you use?

**Comment by marcpages** [comment]
Version 6.1.1 (6A2008a)

**Comment by frantzmiccoli** [comment]
This should be fixed now. See #77 .
