### ISSUE TITLE
'shared' is unavailable problem

### ISSUE THREAD

**Issue by mstftmk** [vikmeup/SCLAlertView-Swift#401]
I used it without problems. This error has begun after installing the OneSignal extension. How can i fix this?
Thanks.

![ekran resmi 2018-04-01 00 10 44](https://user-images.githubusercontent.com/21090784/38761327-67f6fbd8-3f8a-11e8-80e0-6524f8a35b16.png)

**Comment by Nikooos** [comment]
Is this fixed? Because you closed it, but I have the same problem.
