### ISSUE TITLE
"Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value"

### ISSUE THREAD

**Issue by Iainmon** [vikmeup/SCLAlertView-Swift#404]
SCLAlertView.swift
Line 712

If you try and run my last commit "SCL" at https://github.com/Nexal-Technologies/Hawaiian-Weather Xcode will compile it, but will throw an error...

**Comment by Iainmon** [comment]
For some reason, this error would only happen when an alert was called in the `override func viewDidLoad()`. Anywhere else, it seems to be ok.

**Comment by vikmeup** [comment]
👍
