### ISSUE TITLE
Only able to make it work on initial view controller

### ISSUE THREAD

**Issue by Rogog** [vikmeup/SCLAlertView-Swift#41]
Hi 

Firstly, thank you for this alert view.  I really like it!

I am having an issue however with it that. 

1.  When the alert view is presented in the initial view controller - ALERTS WORK!
2. When the user goes through the view controllers - ALERTS NO LONGER WORK :(

Could you advise a novice developer as to why and what I should be looking out for?

**Comment by nadirov** [comment]
having the same issue. Temporary solution was importing SCLAlertView-ObjectiveC

**Comment by mrctito** [comment]
I have the same issue.

Please, how do I import and use  SCLAlertView-ObjectiveC in my swift project?

Thank you!

**Comment by gbertb** [comment]
May want to look into this https://github.com/vikmeup/SCLAlertView-Swift/issues/38
