### ISSUE TITLE
Change circle image color

### ISSUE THREAD

**Issue by severinewillez** [vikmeup/SCLAlertView-Swift#412]
I would like to be able to change the color of the exclamation point that is in the blue bubble. How can I do it ?

![img_2526](https://user-images.githubusercontent.com/38129532/43136332-a9e1e4b4-8f48-11e8-850d-d52084eda029.PNG)

Thanks.

**Comment by arseniybanayev** [comment]
You can change it by supplying `colorStyle: ` in the `showEdit()` (or related) function.

```swift
alert.showEdit("Title", subTitle: "Subtitle", colorStyle: 0xFFFFFF)
```

Note that it takes a `UInt`, not a `UIColor`, so do you can do something like this:

```swift
UIColor color;
var red: CGFloat = 0, green: CGFloat = 0, blue: CGFloat = 0, alpha: CGFloat = 0
if color.getRed(&red, green: &green, blue: &blue, alpha: &alpha) {
    var colorAsUInt: UInt = 0
    colorAsUInt += UInt(red * 255.0) << 16 + UInt(green * 255.0) << 8 + UInt(blue * 255.0)
}
```

**Comment by algrid** [comment]
@arseniybanayev is right, and with current version in master you can use `UIColor` directly
