### ISSUE TITLE
Xcode 10, Swift 4.2 support

### ISSUE THREAD

**Issue by asadali737** [vikmeup/SCLAlertView-Swift#421]
It's giving warning for swift 4.2.

**Comment by mduttondev** [comment]
My PR #422 was merged this morning. Shouldnt be long at this point. Just needs to be released.

**Comment by vikmeup** [comment]
@mduttondev thanks!

**Comment by IsmailHassanein** [comment]
Would you please release it so it updates in cocoapods? Thanks.

**Comment by yaminaanjar** [comment]
Hello, I'm using cocoapods and It's giving warning for swift 4.2
