### ISSUE TITLE
Swift 5 Support w/ Cocoapods

### ISSUE THREAD

**Issue by jlaws** [vikmeup/SCLAlertView-Swift#445]
## Expected Results

No warning to convert SCLAlertView.framework to Swift 5

## Actual Results

Xcode created warnings to convert SCLAlertView.framework to Swift 5

## Steps to Reproduce

Build the cocoapod in Xcode 10.2

**Comment by siddharth-prajapati** [comment]
try this file if you are facing error after auto correct
[SCLAlertView.swift.zip](https://github.com/vikmeup/SCLAlertView-Swift/files/3114144/SCLAlertView.swift.zip)

**Comment by mouness2020** [comment]
pod 'SCLAlertView' , :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git'

**Comment by jlaws** [comment]
ping

**Comment by jlaws** [comment]
@vikmeup

**Comment by jlaws** [comment]
ping

**Comment by idrissbenkhedija** [comment]
I think I have the same problem, any thoughts? 

<img width="529" alt="Capture d’écran 2019-07-09 à 22 29 44" src="https://user-images.githubusercontent.com/49107386/60921674-5a4ae880-a29b-11e9-8c03-18b67f42b424.png">

**Comment by Jaspur** [comment]
@vikmeup ^

**Comment by jlaws** [comment]
Just remove the pod, it’s no longer maintained
