### ISSUE TITLE
Paragraph text box

### ISSUE THREAD

**Issue by ebenezer103** [vikmeup/SCLAlertView-Swift#448]
How can I get a text field box that looks like a paragraph text field box, so users can fit more text into the box?

**Comment by lamsaitat** [comment]
@ebenezer103 do you mean a TextView? 
![Simulator Screen Shot - iPhone XS - 2019-05-07 at 17 09 39](https://user-images.githubusercontent.com/997150/57279000-4512db80-70eb-11e9-8a22-12aa16882496.png)

**Comment by ebenezer103** [comment]
yes that exactly please

**Comment by lamsaitat** [comment]
@ebenezer103  Use addTextView() instead of addTextField()

**Comment by ebenezer103** [comment]
Worked perfectly, thank you for your help. I know you are going to close the issue, but how would I go about changing the overall colour from the default colour to another colour.

**Comment by lamsaitat** [comment]
From SCLAlertViewExample/ViewController.swift:179 - 182

`let icon = UIImage(named:"custom_icon.png")
        let color = UIColor.orange
        
        _ = alert.showCustom("Custom Color", subTitle: "Custom color", color: color, circleIconImage: icon!)`

Is this what you're after?

**Comment by ebenezer103** [comment]
```
            let appearance = SCLAlertView.SCLAppearance(
                kTitleFont: UIFont(name: "HelveticaNeue", size: 0)!,
                kTextFont: UIFont(name: "HelveticaNeue", size: 12)!,
                kButtonFont: UIFont(name: "HelveticaNeue-Bold", size: 14)!,
                showCloseButton: false
            )
            
            let alert = SCLAlertView(appearance: appearance)
            
            // Add a text field
            //let alert = SCLAlertView()
            let txt = alert.addTextView()
            alert.addButton("Done") {
                print("Text value: \(txt.text!)")
            }
            alert.showEdit("", subTitle: "What can the organisation improve on?")

```


This is my code so far when I attempt to implement it and place the code you gave me into it, it doesn't work.

**Comment by lamsaitat** [comment]
> ```
>             let appearance = SCLAlertView.SCLAppearance(
>                 kTitleFont: UIFont(name: "HelveticaNeue", size: 0)!,
>                 kTextFont: UIFont(name: "HelveticaNeue", size: 12)!,
>                 kButtonFont: UIFont(name: "HelveticaNeue-Bold", size: 14)!,
>                 showCloseButton: false
>             )
>             
>             let alert = SCLAlertView(appearance: appearance)
>             
>             // Add a text field
>             //let alert = SCLAlertView()
>             let txt = alert.addTextView()
>             alert.addButton("Done") {
>                 print("Text value: \(txt.text!)")
>             }
>             alert.showEdit("", subTitle: "What can the organisation improve on?")
> ```
> 
> This is my code so far when I attempt to implement it and place the code you gave me into it, it doesn't work.

You're trying to use showEdit which will give a default colour, and a default image.  If you want to preserve the edit icon you can use this instead, with the extension below.

```
let customColor = UIColor.green
 _ = alert.showEdit("", subTitle: "What can the organisation improve on?", colorStyle: customColor.colorAsUInt)
```


```
// This extension was extracted from SCLAlertView.swift:689
extension UIColor {
    var colorAsUInt: UInt {
        var red: CGFloat = 0, green: CGFloat = 0, blue: CGFloat = 0, alpha: CGFloat = 0
        
        getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        
        var colorAsUInt32 : UInt32 = 0
        colorAsUInt32 += UInt32(red * 255.0) << 16
        colorAsUInt32 += UInt32(green * 255.0) << 8
        colorAsUInt32 += UInt32(blue * 255.0)
        
        return UInt(colorAsUInt32)
    }
}
```

**Comment by ebenezer103** [comment]
Thank you very much, this works!
