### ISSUE TITLE
[v 0.8] SCLAlertView.swift: line 712 caused so many crashes

### ISSUE THREAD

**Issue by ghost** [vikmeup/SCLAlertView-Swift#450]
Dears, I've got so many crashes reported on AppCenter in my app caused by forcing unwrap of UIApplication.shared.keyWindow
SCLAlertView.swift / line 712:
let rv = UIApplication.shared.keyWindow! as UIWindow

I am invoking showTitle method of SCLAlertView from my first view controller's viewDidLoad.

`MAIN THREAD - CRASHED
SCLAlertView
function signature specialization <Arg[0] = Exploded, Arg[1] = Exploded> of SCLAlertView.SCLAlertView.showTitle(_: Swift.String, subTitle: Swift.String, timeout: SCLAlertView.SCLAlertView.SCLTimeoutConfiguration?, completeText: Swift.String?, style: SCLAlertView.SCLAlertViewStyle, colorStyle: Swift.UInt?, colorTextButton: Swift.UInt?, circleIconImage: __C.UIImage?, animationStyle: SCLAlertView.SCLAnimationStyle) -> SCLAlertView.SCLAlertViewResponder SCLAlertView.swift:712
SCLAlertView
SCLAlertView.SCLAlertView.showTitle(_: Swift.String, subTitle: Swift.String, style: SCLAlertView.SCLAlertViewStyle, closeButtonTitle: Swift.String?, timeout: SCLAlertView.SCLAlertView.SCLTimeoutConfiguration?, colorStyle: Swift.UInt?, colorTextButton: Swift.UInt, circleIconImage: __C.UIImage?, animationStyle: SCLAlertView.SCLAnimationStyle) -> SCLAlertView.SCLAlertViewResponder SCLAlertView.swift:0
function signature specialization <Arg[0] = Dead, Arg[2] = Dead> of static Utilities.showAlert(_: __C.UIViewController, messageToDisplay: Swift.String) -> () Utilities.swift:44`

Utilities.swift:44 looks like this:
`SCLAlertView().showTitle("Note", subTitle: messageToDisplay, style: .info, closeButtonTitle: "Ok", timeout: nil, colorStyle: 0xE3711F, colorTextButton: 0xFFFFFF, circleIconImage: nil, animationStyle: .topToBottom)`

And it is being invoked upon to the completion of an API call.

Thanks

**Comment by algrid** [comment]
fixed in master
