### ISSUE TITLE
Project crashes after updating Xcode.

### ISSUE THREAD

**Issue by cyye2** [vikmeup/SCLAlertView-Swift#459]
My project can normally work until I update the Xcode to Version 11.0 (11A420a).
Now,When it runs in a little while,it crashes.The error message is as follows:

dyld: Symbol not found: _OBJC_CLASS_$__TtCs12_SwiftObject
  Referenced from: /Users/qizijia/Library/Developer/CoreSimulator/Devices/8B40226A-A7D4-4915-9982-9C8CEF77F24B/data/Containers/Bundle/Application/4B75826C-5FEE-4EB3-85EE-23477B0ED2BD/IRIS iOS.app/Frameworks/SCLAlertView.framework/SCLAlertView
  Expected in: /Library/Developer/Toolchains/swift-5.0.1-RELEASE.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCore.dylib
in /Users/qizijia/Library/Developer/CoreSimulator/Devices/8B40226A-A7D4-4915-9982-9C8CEF77F24B/data/Containers/Bundle/Application/4B75826C-5FEE-4EB3-85EE-23477B0ED2BD/IRIS iOS.app/Frameworks/SCLAlertView.framework/SCLAlertView
 
What can I do to address the problem?
Thanks in advance.

**Comment by accfews** [comment]
Try deleting any derived data, Carthage builds etc and retry

**Comment by algrid** [comment]
Not sure what that was, but currently the project works fine in the recent Xcode version.
