### ISSUE TITLE
Carthage Integration

### ISSUE THREAD

**Issue by juliengdt** [vikmeup/SCLAlertView-Swift#46]
All is in the title: Cocoapods is good but many developers are migrating from pods to carthage:

https://github.com/Carthage/Carthage

If i try to 'carthage' it into my Cartfile with "github "vikmeup/SCLAlertView-Swift" " and it show me:

       Project "SCLAlertViewExample.xcodeproj" has no shared schemes
       If you believe this to be an error, please file an issue with the maintainers at https://github.com/vikmeup/SCLAlertView-Swift/issues/new

**Comment by prine** [comment]
Yeah, Carthage support would be nice!

**Comment by alec-c4** [comment]
+100500

**Comment by vikmeup** [comment]
@juliengdt closed by https://github.com/vikmeup/SCLAlertView-Swift/pull/62

**Comment by sirvine** [comment]
FYI — I'm still getting `Dependency "SCLAlertView-Swift" has no shared framework schemes` on `carthage update` with `github "vikmeup/SCLAlertView-Swift" >= 0.4.2` in Cartfile.

**Comment by vikmeup** [comment]
@sirvine feel free to submit pull request. Thanks.
