### ISSUE TITLE
Dark Mode support?

### ISSUE THREAD

**Issue by Sweeper777** [vikmeup/SCLAlertView-Swift#460]
`SCLAlertView` still has a while background in dark mode. This looks especially bad if there is a text field:

<img width="266" alt="スクリーンショット 2019-10-20 9 36 22" src="https://user-images.githubusercontent.com/13585047/67156969-63793600-f31d-11e9-8240-ac719f8df5b6.png">

**Comment by jeffbailey** [comment]
I worked around this by using SCLAppearance, but it's a pain. Not sure about using a text field though. The one issue is that the contentViewBorder uses a cgColor in the setup method and this is tricky if you override system appearance with overrideUserInterfaceStyle property on a view controller.

**Comment by algrid** [comment]
should be fixed in https://github.com/vikmeup/SCLAlertView-Swift/pull/502
