### ISSUE TITLE
Crash at UIApplication.shared.keyWindow! as UIWindow

### ISSUE THREAD

**Issue by theofficejackpot** [vikmeup/SCLAlertView-Swift#474]
Hi, please help me add some code to prevent the crash at line 712 in SCLAlertView.swift

open func showTitle(_ title: String, subTitle: String, timeout: SCLTimeoutConfiguration?, completeText: String?, style: SCLAlertViewStyle, colorStyle: UInt?=0x000000, colorTextButton: UInt?=0xFFFFFF, circleIconImage: UIImage? = nil, animationStyle: SCLAnimationStyle = .topToBottom) -> SCLAlertViewResponder {
        selfReference = self
        view.alpha = 0
        view.tag = uniqueTag
        view.accessibilityIdentifier = uniqueAccessibilityIdentifier
        let rv = UIApplication.shared.keyWindow! as UIWindow

>>Crashes at line above
iOS 14, iPhone, Swift

**Comment by algrid** [comment]
this should be fixed in master currently
