### ISSUE TITLE
Add ability to show alert without icon

### ISSUE THREAD

**Issue by learnwithgabbar** [vikmeup/SCLAlertView-Swift#477]

**Comment by CHENG-LIANG1** [comment]
just set showCircularIcon to false

`        let appearance = SCLAlertView.SCLAppearance(
            kTitleFont: UIFont(name: "HelveticaNeue", size: 20)!,
            kTextFont: UIFont(name: "HelveticaNeue", size: 14)!,
            kButtonFont: UIFont(name: "HelveticaNeue-Bold", size: 14)!,
            showCloseButton: false,
            showCircularIcon: false,
            contentViewCornerRadius: 15, buttonCornerRadius: 10
        )`

**Comment by algrid** [comment]
yep, @CHENG-LIANG1 is right, something like this:

```
let appearance = SCLAlertView.SCLAppearance(
    showCircularIcon: false
)

SCLAlertView(appearance: appearance).showInfo("Hello")
```
