### ISSUE TITLE
Examples in read me throw compile errors 

### ISSUE THREAD

**Issue by adamdahan** [vikmeup/SCLAlertView-Swift#48]
Your examples of usage also throw compile errors 

Here is an example of one: 
SCLAlertView().showNotice(self, title: "Hello Notice", subTitle: "This is a more descriptive notice text.") // Notice

This error is: Missing argument for parameter coder in call.

**Comment by pekpon** [comment]
+1

**Comment by vikmeup** [comment]
Fixed now.

**Comment by pekpon** [comment]
Thanks!
