### ISSUE TITLE
Examples project doesn't even launch. 

### ISSUE THREAD

**Issue by adamdahan** [vikmeup/SCLAlertView-Swift#49]
Your example project doesn't even launch.

**Comment by vikmeup** [comment]
What version of Xcode do you use?

**Comment by adamdahan** [comment]
Xcode 6.2. Just the latest public release version.

**Comment by digitaldesaster** [comment]
yes, unfortunately it does not work at all

**Comment by digitaldesaster** [comment]
upgrading to Xcode 6.3 and clean the build before compiling did helped..

**Comment by vikmeup** [comment]
@adamdahan, please use Xcode 6.3
