### ISSUE TITLE
com.apple.main-thread SCLAlertView.swift showHTMLTitle / showHTMLInfo

### ISSUE THREAD

**Issue by FazilButev** [vikmeup/SCLAlertView-Swift#499]
My application is constantly crashing and it gives the logs I wrote below as an error. 
I put firebase logs below. I would appreciate it if you could help.

Crashed: com.apple.main-thread
0  MSRS                           0x97044 showHTMLTitle + 1265 (SCLAlertView.swift:1265)
1  MSRS                           0x95a84 showHTMLInfo + 768 (SCLAlertView.swift:768)
2  MSRS                           0x2b50ec showInfoMessage + 59 (PopupHandler.swift:59)
3  MSRS                           0x1067b8 specialized closure #2 in closure #1 in handle #1 <A>() in ServiceManager.sendRequest<A>(urlRequest:completion:) + 4305840056
4  MSRS                           0x93b4 <name omitted> + 4304802740 (<compiler-generated>:4304802740)
5  libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
6  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
7  libdispatch.dylib              0x45858 _dispatch_main_queue_drain + 888
8  libdispatch.dylib              0x454d0 _dispatch_main_queue_callback_4CF$VARIANT$armv81 + 36
9  CoreFoundation                  0x4e0d4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
10 CoreFoundation                 0xb5f8 __CFRunLoopRun + 2544
11 CoreFoundation                  0x1e250 CFRunLoopRunSpecific + 572
12 GraphicsServices               0x1988 GSEventRunModal + 160
13 UIKitCore                            0x4e5a94 -[UIApplication _run] + 1080
14 UIKitCore                            0x27efd4 UIApplicationMain + 336
15 MSRS                                  0x6e3c main + 21 (AppStoreDelegate.swift:21)
16 ???                                       0x1039b44d0 (Missing)

**Comment by algrid** [comment]
You're probably using a modified version of the library. Maybe you have added some code from here https://github.com/vikmeup/SCLAlertView-Swift/issues/348

The problem is the `showHTMLTitle` function that you have added. Look at the line where crash happens, maybe that will help.
