### ISSUE TITLE
only available on ios 13 or newer

### ISSUE THREAD

**Issue by UtkuDalmaz** [vikmeup/SCLAlertView-Swift#504]
After the last commit to the master, I started getting errors.

![Screenshot 2023-10-26 at 17 19 35](https://github.com/vikmeup/SCLAlertView-Swift/assets/2130592/9a116456-c01d-4d76-91fd-322dfceb1478)

Project's deployment target is ios 13.0

Any idea? @algrid

**Comment by UtkuDalmaz** [comment]
No, i don't need support for below iOS 12. The deployment target is iOS 13, but why am I getting this error?

**Comment by algrid** [comment]
How did you integrate the library? Are you using SPM or something else?

**Comment by UtkuDalmaz** [comment]
I am using SPM and master branch

**Comment by algrid** [comment]
Hmm, I guess we should change `.iOS(.v8)` to `.iOS(.v13)` here https://github.com/vikmeup/SCLAlertView-Swift/blob/master/Package.swift

Let me try it.

**Comment by algrid** [comment]
@UtkuDalmaz can you update you project and try again? I updated Package.swift

**Comment by UtkuDalmaz** [comment]
@algrid, I cannot update now. It gives. Invalid Manifest error.

**Comment by UtkuDalmaz** [comment]
Just tried a fork now, and it worked. Please copy this. https://github.com/c0909h1179/SCLAlertView-Swift/blob/master/Package.swift

**Comment by algrid** [comment]
Turns out it was enough just to update the `swift-tools-version` version, I just merged the fix and was able to import the package successfully. (had to remove the cache in  ~/Library/Caches/org.swift.swiftpm/repositories to make it work though)
