### ISSUE TITLE
Standard Button always hides the AlertView?

### ISSUE THREAD

**Issue by digitaldesaster** [vikmeup/SCLAlertView-Swift#51]
Hi, i cant find an option to change the behavior of the standard button. What i want to achieve is an alertview with only one button and an custom action.

thanks in advance

**Comment by alexcosmin** [comment]
Did you find out if this is possible? I am interested in the same thing.

**Comment by x140yu** [comment]
I need the same thing

**Comment by tonymwinters** [comment]
```alert.showCloseButton = false```

**Comment by vikmeup** [comment]
@digitaldesaster let me know if @tonymwinters solution worked for you.
