### ISSUE TITLE
Use of unresolved identifier 'SCLAlertView'

### ISSUE THREAD

**Issue by aradhell** [vikmeup/SCLAlertView-Swift#52]
Hi,
 Installed via Cocoapods and Podfile , (gem install cocoapods --pre Fetching: cocoapods-core 0.37.0.beta.1.gem (100%)) xCode Version 6.3 (6D570)

--
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'SwiftHTTP', '~> 0.9.4'
pod 'JSONJoy-Swift', '~> 0.9.2'
pod 'SCLAlertView'

SwiftHTTP and other is working but SCLAlertView cudnt resolved, Use of unresolved identifier 'SCLAlertView', if i add import SCLAlertView that time gives no such module SCLAlertView

Thank you

**Comment by kesar** [comment]
I dont know if this is going to solve your problem, but I am using:
```
pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git', :branch => 'master'
```

**Comment by sergiot** [comment]
@kesar, it does help. Thanks.

**Comment by rizwan95** [comment]
I am having the same problem and the solution doesn't work for me.

**Comment by deepukjayan** [comment]
This issue still exists.

**Comment by vikmeup** [comment]
@rizwan95 what version of Xcode do you use?

**Comment by mitesh21** [comment]
@vikmeup  i have xCode 7.1.1 but still not working

**Comment by gannimet** [comment]
I have the same problem with XCode 9.0

**Comment by Spark3000** [comment]
Same here. XCode 9.0

**Comment by thamerfa** [comment]
same here

**Comment by thamerfa** [comment]
Adding Foundation.framework to your project solved the problem.
