### ISSUE TITLE
no fading when tapping 'Done' (double calling 'hideView' method) & odd Circle Position

### ISSUE THREAD

**Issue by x8b** [vikmeup/SCLAlertView-Swift#53]
Hello,

First of all, thank you so much for your great work.

- - -

It seems 'hideView' method called twice when the 'Done' button tapped. Due to that 'double function calling' the fading animation always cancels as I titled this issue. It happens not only in my project but in SCLAlertViewExample project as well. Please have a check.

Another one, I found the Y positions of _CircleView & CircleBG_ are a bit irregular in current version. I made a fixed fork for this.

Tested with xcode6.3.1 + Yosemite 10.10.3 / iPhone5 & 6simulator

**Comment by vikmeup** [comment]
@x8b could you submit your PR.

**Comment by HaciKale** [comment]
there is no fading when you add buttons that also uses the hideView().
