### ISSUE TITLE
Doesn´t work with Xcode 6.3.1

### ISSUE THREAD

**Issue by fdorado985** [vikmeup/SCLAlertView-Swift#56]
I updated to Xcode 6.3.1 and i get 7 errors...
I supposed that is for the new version of Swift
Could you or someone take a look?
![captura de pantalla 2015-04-28 a las 3 56 44 p m](https://cloud.githubusercontent.com/assets/10659046/7380167/a21c030a-edbf-11e4-87ad-7ab0e9e37011.png)

**Comment by fdorado985** [comment]
I fix two of them...

The last one... i only wrote a ! instead of ? for the downcast...

And the third one, the method changed... but the another ones i do know how to fix that constructors of init

**Comment by vikmeup** [comment]
@fdorado985 I would be able to fix this next week, unless you would like to send your pull request with changes to Swift 1.2. Thanks

**Comment by maxelbert** [comment]
@fdorado985 You might find [this answer](http://stackoverflow.com/questions/29031270/initializer-does-not-override-a-designated-initializer-from-its-superclass) and [this answer](http://stackoverflow.com/questions/28771896/overriding-method-with-selector-touchesbeganwithevent-has-incompatible-type) useful. Here are the changes I made to clear the errors:

```
public init() {
    super.init(frame: CGRectZero)
}
```
```
public init() {
    super.init(nibName: nil, bundle: nil)
```
```
override public func touchesEnded(touches:Set<NSObject>, withEvent event:UIEvent) {
```
The last issue just requires an **as!** downcast, as you mentioned.

**NOTE:** Though I got those errors to go away, I am still experiencing a "Use of unresolved identifier 'SCLAlertView'" error, but I think that is unrelated.

**Comment by fdorado985** [comment]
Hi @maxelbert  somebody made a pull request i guess, i supposed it was you, i did exactly that, and i didn't have issues, it works for me, thank you so much

**Comment by captainchung** [comment]
I still got those compile errors.  was the pull request not made?

**Comment by vikmeup** [comment]
@captainchung could you verify getting from master branch? 

https://github.com/vikmeup/SCLAlertView-Swift/pull/50 this should fix it.

**Comment by captainchung** [comment]
I see, I had assumed the pod spec was pointing to the latest in the master
branch where it is actually pointing to 0.3  .  Thanks for responding.

On Wed, May 6, 2015 at 9:30 PM, Viktor Radchenko <notifications@github.com>
wrote:

> @captainchung <https://github.com/captainchung> could you verify getting
> from master branch?
>
> #50 <https://github.com/vikmeup/SCLAlertView-Swift/pull/50> this should
> fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vikmeup/SCLAlertView-Swift/issues/56#issuecomment-99709231>
> .
>



-- 
Regards,
Matt

**Comment by ZaidPathan** [comment]
Is it working now, so that I can integrate it in my project?

**Comment by vikmeup** [comment]
Updated.

**Comment by ZaidPathan** [comment]
Ok.thanks.
