### ISSUE TITLE
Add Image to SCLAlertView

### ISSUE THREAD

**Issue by confile** [vikmeup/SCLAlertView-Swift#57]
It would be great the add an ImageView to the SCLAlertView.

**Comment by kyegeorge** [comment]
+1

**Comment by vikmeup** [comment]
@confile as a top header?

**Comment by kyegeorge** [comment]
Correct. its set in the [Objective-C ver](https://github.com/dogo/SCLAlertView) using
```Objective-C
[alert showCustom:self image:[UIImage imageNamed:@"git"] color:color title:@"Custom" subTitle:@"Add a custom icon and color for your own type of alert!" closeButtonTitle:@"OK" duration:0.0f]; // Custom
```
![Example](https://raw.githubusercontent.com/dogo/SCLAlertView/master/ScreenShots/ScreenShot3.png)

**Comment by vikmeup** [comment]
It should not be hard to implement. In ShowTitle function we need to take extra parameter of UIImage and then set it to internal variable `iconImage`. 

Feel free to send pull request. I'm currently busy with another project. Thanks!
