### ISSUE TITLE
AlertView without the default button

### ISSUE THREAD

**Issue by amjohnno** [vikmeup/SCLAlertView-Swift#59]
Is it possible to show an AlertView with just one button that performs a function?

As far as I can tell, I can't get rid of the default "Done" button, which only seems to allow me to close the alert. If possible, I would like this Done button to either allow me to segue when pressed, or to be hidden completely so that I can use a custom button to perform this function.

Thanks.

**Comment by kesar** [comment]
:+1:

**Comment by ncerezo** [comment]
This is already possible. My pull request was accepted a few days ago and it had this feature:

    let alert = SCLAlertView()
    alert.showCloseButton = false

That's it.
So this issue should be closed.

I plan to add the ability to set a closure to be run when the view is closed. That would allow to use the default close button when you need it to perform certain functions.
However, showCloseButton would still be useful.

**Comment by kesar** [comment]
it has a typo:
```showCloseButtton```

**Comment by ncerezo** [comment]
You're right!
Thanks for pointing out.
I'll send a new pull request.

**Comment by hons82** [comment]
If you import it using Cocoapods it will not be accessible right now. You'd need to update it with public
```Swift
public var showCloseButton = true
```

**Comment by ivangodfather** [comment]
but if you make it public you have an error when dismissing, unrecognizer selector...

**Comment by ivangodfather** [comment]
@ncerezo @hons82  any ideas?

**Comment by hons82** [comment]
Yes? Where u get that?
On which method call?!? 
Cocoapods or manual installation?

~hons

**Comment by ivangodfather** [comment]
Cocoapods

Iván

**Comment by ivangodfather** [comment]
I can't reproduce it like before, dunno why, its getting me to app delegate failure, btw i dont like modifying my pods manually changing the scope of a var to public since in a future realase when i update my changes will be overwriten. Im thinking using objc version with bridging header since that version hasnt got this problem.

**Comment by ivangodfather** [comment]
@hons82 have you looked at it?

**Comment by hons82** [comment]
Yes, but I don't c the problem. Of course you should change the pod... the author needs to do that, if he likes to. It's not the only possibility to make that accessible.
He could ad a setter like function for it or provide only the setter in public [(similar ashere)](http://stackoverflow.com/questions/25708439/swift-readonly-external-readwrite-internal-property)

For the bridging header... this works as long as you don't need to use any swift pods in your project. Those require ```use_frameworks!``` and then it's not accessible anymore

**Comment by ivangodfather** [comment]
Yes, i am using swift pods with use_frameworks!

On 29 June 2015 at 07:58, Hannes <notifications@github.com> wrote:

> Yes, but I don't c the problem. Of course you should change the pod... the
> author needs to do that, if he likes to. It's not the only possibility to
> make that accessible.
> He could ad a setter like function for it or provide only the setter in
> public (similar ashere)
> <http://stackoverflow.com/questions/25708439/swift-readonly-external-readwrite-internal-property>
>
> For the bridging header... this works as long as you don't need to use any
> swift pods in your project. Those require use_frameworks! and then it's
> not accessible anymore
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vikmeup/SCLAlertView-Swift/issues/59#issuecomment-116456021>
> .
>



-- 
Este mensaje se dirige a su destinatario y puede contener información
confidencial sometida a secreto profesional o cuya divulgación esté
prohibida por la Legislación Vigente. Cualquier persona distinta a su
destinataria tiene prohibida su reproducción, uso, divulgación o impresión
total o parcial. Si ha recibido este mensaje por error, notifíquelo de
inmediato al remitente borrando el mensaje original juntamente con sus
ficheros anexos. Gracias.

**Comment by frantzmiccoli** [comment]
FYI I have used the last revision by tweaking my Podfile to use a specific branch or commit.

To use a specific branch:

```ruby
pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git', :branch => 'master'
```

To target a specific revision:

```ruby
pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git', :commit => 'e8fd6756722bc460d96cde2c90a833e20e943a2d'
```

Just know that **I have experienced an issue** using this feature, see #76.

**Comment by ivangodfather** [comment]
ok, thx you, keep me updated!

**Comment by ispha** [comment]
I could do this following their documentation by making an appearance style for the Alert then assigning it to my alert . It works perfectly .

   let appearance = SCLAlertView.SCLAppearance(
           
            showCloseButton: false
        )
let alertView = SCLAlertView(appearance: appearance)
