### ISSUE TITLE
Cocoapods Version Out of Date

### ISSUE THREAD

**Issue by taylorfriesen** [vikmeup/SCLAlertView-Swift#60]
The most recent version of SCLAlertView-Swift on Cocoapods is 0.3.1, which suffers from issue #56 - not being updated to support Swift 1.2. The master branch (which is tag 0.3.2) includes the required fixes, and so it would be great if the Cocoapods version could be updated to match the latest master.

**Comment by tbaranes** [comment]
I agree. I'm targeting directly your latest release:
`pod 'SCLAlertView', :git => "https://github.com/vikmeup/SCLAlertView-Swift.git", :tag => "0.3.2"`

but it will be better to have a pod up to date

**Comment by vikmeup** [comment]
Updated.
