### ISSUE TITLE
This doesn't work at all in latest version of Swift 1.2 

### ISSUE THREAD

**Issue by adamdahan** [vikmeup/SCLAlertView-Swift#64]
Just try to run the code it's a no go. 

Give this a shot as an example: -> 
        SCLAlertView().showInfo(self, title: "Hello Info", subTitle: "This is a more descriptive info text.") // Info

Taken directly from your git read me

**Comment by kesar** [comment]
This would work:
```
SCLAlertView().showInfo("Hello Info", subTitle: "This is a more descriptive info text.") // Info
```

**Comment by vikmeup** [comment]
Please upgrade your Swift to 2.0.
