### ISSUE TITLE
Argument 'subTitle' must precede 'title'

### ISSUE THREAD

**Issue by rizwan95** [vikmeup/SCLAlertView-Swift#67]
I am getting the following error "Argument 'subTitle' must precede 'title' "

My code is correct only , and here is the snippet,      

let alert = SCLAlertView()
                alert.addButton("First Button", target:self, selector:Selector("firstButton"))
                alert.addButton("Second Button") {
                    println("Second button tapped")
                }
                alert.showSuccess(self, title: "Button View", subTitle: "This alert view has buttons")

**Comment by ncerezo** [comment]
showSuccess (and the rest of showXXX functions) accept a first parameter (unnamed) for title, then subTitle, and then other optional parameters.

So your code should be:
```swift
alert.showSuccess( "Button View", subTitle: "This alert view has buttons" )
```

**Comment by mehmetvefa** [comment]
I had same problem and this is the solution. Thanks.
