### ISSUE TITLE
Custom style

### ISSUE THREAD

**Issue by cvburgess** [vikmeup/SCLAlertView-Swift#71]
having a custom style with a custom icon/color would be great

similar to https://bitbucket.org/sprygroupllc/sclalertview

**Comment by allaire** [comment]
:+1: Any idea why the obj-c clone has more feature? different maintainers?

**Comment by allaire** [comment]
Also, since you can include swift code in obj-c code, I don't understand why there's two projects side by side :)

**Comment by cvburgess** [comment]
@allaire I think the point of this was to be a pure swift implementation so you can keep debugging and extending in one language across your project. But good point!

**Comment by jdgong** [comment]
@allaire I totally agree. I am writing in Swift but I have to convert to use the Objc version of this library just because they have more features, especially for customization. Is there a possibility that they can combine and maybe just make it two branches?

**Comment by FelipeNBrito** [comment]
I've created a custumizable alert. I think it helps on this issue. https://github.com/vikmeup/SCLAlertView-Swift/pull/196

**Comment by cvburgess** [comment]
Closing this assuming #196 gets merged it's exactly what I was looking for. Thank you @FelipeNBrito !
