### ISSUE TITLE
Any plan to support Swift 2 and Xcode7?

### ISSUE THREAD

**Issue by kamoljan** [vikmeup/SCLAlertView-Swift#73]

**Comment by vikmeup** [comment]
@kamoljan I do not have Xcode 7 yet installed, pull request are welcome. Thanks

**Comment by calvinchengx** [comment]
PR submitted for Swift 2/Xcode 7. Ref #91

**Comment by ogezue** [comment]
XCode7 Swift2.0 shows errors:
<img width="265" alt="bildschirmfoto 2015-08-21 um 16 54 21" src="https://cloud.githubusercontent.com/assets/2361031/9411280/64a0902a-4825-11e5-85ec-f5ee1ae8f8bb.png">

**Comment by vikmeup** [comment]
Support for 2.0 released.
