### ISSUE TITLE
Using showCloseButton raises an EXC_BAD_ACCESS error once tapping a button

### ISSUE THREAD

**Issue by frantzmiccoli** [vikmeup/SCLAlertView-Swift#76]
### Reproduciblity

I have been experiencing this in one of my project and been able to reproduce this just starting from the simple "Single View Application template", adding a button and connecting it to the IBOutlet below:

```swift
import UIKit

import SCLAlertView

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    @IBAction func onTouchUpInside(sender: AnyObject) {
        let alertView = SCLAlertView()
        
        // if you comment the line below you won't get anymore crash
        alertView.showCloseButton = false
        
        alertView.addButton("button 1", action: {
            println("action 1")
        })
        
        alertView.showError("Some Error", subTitle: "Some text")
        
    }

}
```

I have been using the last revision e8fd6756722bc460d96cde2c90a833e20e943a2d installed through CocoaPods. The Podfile is:

```ruby
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git', :branch => 'master'
```

### Environment

The problem has been reproduced using:

* Swift 1.2
* XCode 6.3.2 and 6.4.3
* iOS 8.3

### More information

Unfortunately the error is not very explicit, though tweaking on my original project (adding breakpoints) I saw at some point some `unrecognized selector sent to instance` that was related with handling the tap on the buttons and the buttons state. I am not able to get that full message back unfortunately, nor I have yet found a solution to this bug. 

ccing @ncerezo author of the `showCloseButton` feature visible in 2c29b1621c0f59ac2d6a62ad86fb4523833e050a that looks ok to me. I am curious to know if you reproduce this as well.

**Comment by frantzmiccoli** [comment]
By digging a bit more and enabling some debugging components. I got this:

```
*** -[SCLAlertView.SCLAlertView dismissKeyboard]: message sent to deallocated instance 0x13c5092f0
```

The alertView memory seems to be released because no pointer are using it anymore...

This doesn't crash.

```
import UIKit

import SCLAlertView

class ViewController: UIViewController {

    var alertView = SCLAlertView()

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    @IBAction func onTouchUpInside(sender: AnyObject) {
        alertView = SCLAlertView()

        // if you comment the line below you won't get anymore crash
        alertView.showCloseButton = false

        alertView.addButton("button 1", action: {
            println("action 1")
        })

        alertView.showError("Some Error", subTitle: "Some text")

    }

}
```

**Comment by vikmeup** [comment]
Closed: https://github.com/vikmeup/SCLAlertView-Swift/pull/77
