### ISSUE TITLE
Podfile update?

### ISSUE THREAD

**Issue by rkorimba** [vikmeup/SCLAlertView-Swift#78]
Hi vikmeup, I'm integrating this using Cocoapods into a new app, and after running pod update everything was pulled in correctly, but did not include the recent changes that you merged. Is there an easy way to fix that?

**Comment by frantzmiccoli** [comment]
Short term solution in a previous issue: https://github.com/vikmeup/SCLAlertView-Swift/issues/59#issuecomment-118492576

Mid term solution: update the pod. I was about to suggest this but I am working on a couple improvements and I think this can only be done by @vikmeup .

**Comment by rkorimba** [comment]
Thx :)

**Comment by allaire** [comment]
Yep, a pod update would be nice.

In the meantime, do `pod "SCLAlertView", :head`

**Comment by vikmeup** [comment]
Thanks you guys. Just pushed latest to 0.4.1
