### ISSUE TITLE
ios 7.1 fatal error

### ISSUE THREAD

**Issue by orkunbaba** [vikmeup/SCLAlertView-Swift#86]
I use xcode 6.4 and when i run this code in ios 7.1 simulator this error becomes

for line 357
let rv = UIApplication.sharedApplication().keyWindow! as UIWindow
        
fatal error: unexpectedly found nil while unwrapping an Optional value

is any solution for ios 7.1

regards
Orkun

**Comment by ncerezo** [comment]
This works for me with iOS7 and up:

    let rv = UIApplication.sharedApplication().keyWindow?.subviews.last as! UIView

**Comment by ncerezo** [comment]
However, keyWindow shouldn't be nil.
My problem with that line is that it broke the view with iOS7 and landscape mode.

**Comment by iThanh** [comment]
Same issue.
Anybody fixed it, please?
