### ISSUE TITLE
How do I get the "closeButtonTitle" to not show up at all? 

### ISSUE THREAD

**Issue by FezHacker** [vikmeup/SCLAlertView-Swift#87]
How do I get the "closeButtonTitle" to not show up at all? 

I am using the showWait and I dont want the closeButtonTitle at all.

- Thanks for the geart Alert Views

**Comment by ncerezo** [comment]
showCloseButton = false

Narciso Cerezo

**Comment by FezHacker** [comment]
How would I go about implementing that?

    var alert = SCLAlertView()
            alert.showWait("Saving", subTitle: "Saving your update", duration: 3)
            showCloseButton = false

**Comment by ncerezo** [comment]
Sorry, I'm writing from my phone.

alert.showCloseButton = false

Before showing it.

Narciso Cerezo

**Comment by FezHacker** [comment]
Thanks for all your help!
