### ISSUE TITLE
Keyboard Hiding SCLAlertView

### ISSUE THREAD

**Issue by devilbags** [vikmeup/SCLAlertView-Swift#90]
First of all, Thank you for this great project.

One little problem: After adding textfield to the alert view, whenever keyboard pops up, it's blocking everything below the textview. 

Any advice?

**Comment by wieseljonas** [comment]
Same issue for me! Had to add some code to the classe to fix this. It's not the best solution but works for now

those two nofification in viewdidLoad 

        NSNotificationCenter.defaultCenter().addObserver(self, selector: Selector("keyboardWillShow:"), name:UIKeyboardWillShowNotification, object: nil);
        NSNotificationCenter.defaultCenter().addObserver(self, selector: Selector("keyboardWillHide:"), name:UIKeyboardWillHideNotification, object: nil);


and those 2 functions

      func keyboardWillShow(notification: NSNotification) {
        UIView.animateWithDuration(0.1, animations: { () -> Void in
            let pointMoveY = abs(self.contentView.frame.origin.y - (self.contentView.frame.minY + self.contentView.frame.height/2))
            self.contentView.frame.origin = CGPointMake(self.contentView.frame.origin.x, (self.contentView.frame.origin.y - self.contentView.frame.height/2))
            self.circleBG.frame.origin = CGPointMake(self.circleBG.frame.origin.x, self.circleBG.frame.origin.y - pointMoveY)
        })
        
    }
    
    func keyboardWillHide(notification: NSNotification) {
        UIView.animateWithDuration(0.1, animations: { () -> Void in
            let pointMoveY = abs(self.contentView.frame.origin.y - (self.contentView.frame.origin.y + self.contentView.frame.height/2))
            self.contentView.frame.origin = CGPointMake(self.contentView.frame.origin.x, (self.contentView.frame.origin.y + self.contentView.frame.height/2))
            self.circleBG.frame.origin = CGPointMake(self.circleBG.frame.origin.x, self.circleBG.frame.origin.y + pointMoveY)

        })
    }

**Comment by ogezue** [comment]
Solution from Wieseljonas has one bug: The event keyboardWillShow even fires if the keyboard is visible and the autosuggestion is used... this makes the view fading out of the screen...

**Comment by orangecoding** [comment]
@ogezue @wieseljonas @devilbags see my pullreq. https://github.com/vikmeup/SCLAlertView-Swift/pull/103

**Comment by PhilippeBoisney** [comment]
@orangecoding I just tested your pull request, and it works like a charm :) Thanks !

**Comment by vikmeup** [comment]
Latest changes pushed to cocopoads. Version: 0.4.3

**Comment by orangecoding** [comment]
@PhilippeBoisney no worries ;)
