### ISSUE TITLE
Gives error when compiling code with Xcode 7 beta 6 

### ISSUE THREAD

**Issue by gvimlan95** [vikmeup/SCLAlertView-Swift#95]
This is the error I m getting. 
![screen shot 2015-09-17 at 12 23 43 pm](https://cloud.githubusercontent.com/assets/9544447/9924919/13743aae-5d37-11e5-9d38-deb07e3ff4d6.png)

**Comment by mcvasquez** [comment]
I'm getting the same error using v0.4.1. I think this version does not support Swift 2, but v0.4.2 does. I'm waiting for the last version via cocoapods to test it out.

**Comment by chriscohoat** [comment]
Using Swift 2 I've gotten v0.4.2 to compile successfully...I was seeing the same thing you guys were.

My Podfile has this line: 

```pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git'```

**Comment by mcvasquez** [comment]
Solved, thanks @chriscohoat.

**Comment by orangecoding** [comment]
Why is this not just available over the standard pod *podfile* command?

**Comment by vikmeup** [comment]
should be fixed now.
