### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by ewan34500** [vikmeup/SCLAlertView-Swift#98]
I can launch my app when I want to display an alert this error appear : fatal error: unexpectedly found nil while unwrapping an Optional value

The error line : let rv = UIApplication.sharedApplication().keyWindow! as UIWindow

**Comment by dancingbush** [comment]
Hi, I am getting the same error, 
: let rv = UIApplication.sharedApplication().keyWindow! as UIWindow
 did you find a solution?

**Comment by dancingbush** [comment]
Window must not be set in viewDidLoad so instead I moved code to viewDidAppear and to works fine.

**Comment by ewan34500** [comment]
It's right, now it's working, thanks, but maybe this AlertView can be better if it's work in the ViewDidLoad too ...
